/**
 * This file is auto-generated by scripts/createParticuleRegistry.ts
 * Do not edit this file directly.
 * To update, edit the source files in scripts/user-registry-particule-metadata.ts and run: pnpm generate:registry
 * @version 0.1.0
 * !!!!!!!!!!
 */
export interface RegistryParticuleEntry {
  description: string;
  // relative to src/lib/components/
  file: string;
  name: string;
  npmDependencies: string[];
  registryDependencies: string[];
  // optional tags for categorization
  tags: string[];
}

export type RegistryParticuleData = Record<string, RegistryParticuleEntry>;
const particles: RegistryParticuleData = {
  'accordion-01': {
    description: 'Basic accordion',
    file: 'accordion/accordion-01',
    name: 'Accordion 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['accordion']
  },
  'accordion-02': {
    description: 'Accordion with one panel open',
    file: 'accordion/accordion-02',
    name: 'Accordion 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['accordion']
  },
  'accordion-03': {
    description: 'Accordion allowing multiple panels open',
    file: 'accordion/accordion-03',
    name: 'Accordion 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['accordion']
  },
  'accordion-04': {
    description: 'Controlled accordion',
    file: 'accordion/accordion-04',
    name: 'Accordion 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['accordion']
  },
  'accordion-05': {
    description: '',
    file: 'accordion/accordion-05',
    name: 'Accordion 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-06': {
    description: '',
    file: 'accordion/accordion-06',
    name: 'Accordion 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-07': {
    description: '',
    file: 'accordion/accordion-07',
    name: 'Accordion 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-08': {
    description: '',
    file: 'accordion/accordion-08',
    name: 'Accordion 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-09': {
    description: '',
    file: 'accordion/accordion-09',
    name: 'Accordion 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-10': {
    description: '',
    file: 'accordion/accordion-10',
    name: 'Accordion 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-11': {
    description: '',
    file: 'accordion/accordion-11',
    name: 'Accordion 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-12': {
    description: '',
    file: 'accordion/accordion-12',
    name: 'Accordion 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-13': {
    description: '',
    file: 'accordion/accordion-13',
    name: 'Accordion 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-14': {
    description: '',
    file: 'accordion/accordion-14',
    name: 'Accordion 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-15': {
    description: '',
    file: 'accordion/accordion-15',
    name: 'Accordion 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-16': {
    description: '',
    file: 'accordion/accordion-16',
    name: 'Accordion 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-17': {
    description: '',
    file: 'accordion/accordion-17',
    name: 'Accordion 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-18': {
    description: '',
    file: 'accordion/accordion-18',
    name: 'Accordion 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-19': {
    description: '',
    file: 'accordion/accordion-19',
    name: 'Accordion 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'accordion-20': {
    description: '',
    file: 'accordion/accordion-20',
    name: 'Accordion 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'alert-01': {
    description: 'Basic alert',
    file: 'alert/alert-01',
    name: 'Alert 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert']
  },
  'alert-02': {
    description: 'Alert with icon',
    file: 'alert/alert-02',
    name: 'Alert 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert']
  },
  'alert-03': {
    description: 'Alert with icon and action buttons',
    file: 'alert/alert-03',
    name: 'Alert 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert']
  },
  'alert-04': {
    description: 'Info alert',
    file: 'alert/alert-04',
    name: 'Alert 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert', 'info']
  },
  'alert-05': {
    description: 'Success alert',
    file: 'alert/alert-05',
    name: 'Alert 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert', 'success']
  },
  'alert-06': {
    description: 'Warning alert',
    file: 'alert/alert-06',
    name: 'Alert 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert', 'warning']
  },
  'alert-07': {
    description: 'Error alert',
    file: 'alert/alert-07',
    name: 'Alert 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert', 'error']
  },
  'alert-08': {
    description: '',
    file: 'alert/alert-08',
    name: 'Alert 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'alert-09': {
    description: '',
    file: 'alert/alert-09',
    name: 'Alert 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'alert-10': {
    description: '',
    file: 'alert/alert-10',
    name: 'Alert 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'alert-11': {
    description: '',
    file: 'alert/alert-11',
    name: 'Alert 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'alert-12': {
    description: '',
    file: 'alert/alert-12',
    name: 'Alert 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-01': {
    description: 'Avatar with image and fallback',
    file: 'avatar/avatar-01',
    name: 'Avatar 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-02': {
    description: 'Fallback-only avatar',
    file: 'avatar/avatar-02',
    name: 'Avatar 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-03': {
    description: 'Avatars with different sizes',
    file: 'avatar/avatar-03',
    name: 'Avatar 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-04': {
    description: 'Avatars with different radii',
    file: 'avatar/avatar-04',
    name: 'Avatar 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-05': {
    description: 'Overlapping avatar group',
    file: 'avatar/avatar-05',
    name: 'Avatar 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-06': {
    description: 'Avatar with user icon fallback',
    file: 'avatar/avatar-06',
    name: 'Avatar 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-07': {
    description: 'Avatar with emerald status dot',
    file: 'avatar/avatar-07',
    name: 'Avatar 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-08': {
    description: 'Avatar with muted status dot',
    file: 'avatar/avatar-08',
    name: 'Avatar 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-09': {
    description: 'Rounded avatar with top-right emerald status',
    file: 'avatar/avatar-09',
    name: 'Avatar 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-10': {
    description: 'Avatar with notification badge',
    file: 'avatar/avatar-10',
    name: 'Avatar 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-11': {
    description: 'Rounded avatar with notification badge',
    file: 'avatar/avatar-11',
    name: 'Avatar 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-12': {
    description: 'Avatar with verified badge',
    file: 'avatar/avatar-12',
    name: 'Avatar 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-13': {
    description: 'Small overlapping avatar group',
    file: 'avatar/avatar-13',
    name: 'Avatar 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-14': {
    description: 'Large overlapping avatar group',
    file: 'avatar/avatar-14',
    name: 'Avatar 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar']
  },
  'avatar-15': {
    description: '',
    file: 'avatar/avatar-15',
    name: 'Avatar 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-16': {
    description: '',
    file: 'avatar/avatar-16',
    name: 'Avatar 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-17': {
    description: '',
    file: 'avatar/avatar-17',
    name: 'Avatar 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-18': {
    description: '',
    file: 'avatar/avatar-18',
    name: 'Avatar 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-19': {
    description: '',
    file: 'avatar/avatar-19',
    name: 'Avatar 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-20': {
    description: '',
    file: 'avatar/avatar-20',
    name: 'Avatar 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-21': {
    description: '',
    file: 'avatar/avatar-21',
    name: 'Avatar 21',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-22': {
    description: '',
    file: 'avatar/avatar-22',
    name: 'Avatar 22',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'avatar-23': {
    description: '',
    file: 'avatar/avatar-23',
    name: 'Avatar 23',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'badge-01': {
    description: 'Basic badge',
    file: 'badge/badge-01',
    name: 'Badge 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-02': {
    description: 'Outline badge',
    file: 'badge/badge-02',
    name: 'Badge 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-03': {
    description: 'Secondary badge',
    file: 'badge/badge-03',
    name: 'Badge 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-04': {
    description: 'Destructive badge',
    file: 'badge/badge-04',
    name: 'Badge 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge', 'error']
  },
  'badge-05': {
    description: 'Info badge',
    file: 'badge/badge-05',
    name: 'Badge 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge', 'info']
  },
  'badge-06': {
    description: 'Success badge',
    file: 'badge/badge-06',
    name: 'Badge 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge', 'success']
  },
  'badge-07': {
    description: 'Warning badge',
    file: 'badge/badge-07',
    name: 'Badge 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge', 'warning']
  },
  'badge-08': {
    description: 'Error badge',
    file: 'badge/badge-08',
    name: 'Badge 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge', 'error']
  },
  'badge-09': {
    description: 'Small badge',
    file: 'badge/badge-09',
    name: 'Badge 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-10': {
    description: 'Large badge',
    file: 'badge/badge-10',
    name: 'Badge 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-11': {
    description: 'Badge with icon',
    file: 'badge/badge-11',
    name: 'Badge 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-12': {
    description: 'Badge with link',
    file: 'badge/badge-12',
    name: 'Badge 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'badge-13': {
    description: 'Badge with count',
    file: 'badge/badge-13',
    name: 'Badge 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['badge']
  },
  'banner-01': {
    description: '',
    file: 'banner/banner-01',
    name: 'Banner 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-02': {
    description: '',
    file: 'banner/banner-02',
    name: 'Banner 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-03': {
    description: '',
    file: 'banner/banner-03',
    name: 'Banner 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-04': {
    description: '',
    file: 'banner/banner-04',
    name: 'Banner 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-05': {
    description: '',
    file: 'banner/banner-05',
    name: 'Banner 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-06': {
    description: '',
    file: 'banner/banner-06',
    name: 'Banner 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-07': {
    description: '',
    file: 'banner/banner-07',
    name: 'Banner 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-08': {
    description: '',
    file: 'banner/banner-08',
    name: 'Banner 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-09': {
    description: '',
    file: 'banner/banner-09',
    name: 'Banner 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-10': {
    description: '',
    file: 'banner/banner-10',
    name: 'Banner 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-11': {
    description: '',
    file: 'banner/banner-11',
    name: 'Banner 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'banner-12': {
    description: '',
    file: 'banner/banner-12',
    name: 'Banner 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'breadcrumb-01': {
    description: 'Breadcrumb with menu example',
    file: 'breadcrumb/breadcrumb-01',
    name: 'Breadcrumb 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb', 'dropdown', 'menu']
  },
  'breadcrumb-02': {
    description: 'Breadcrumb with custom separator',
    file: 'breadcrumb/breadcrumb-02',
    name: 'Breadcrumb 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb']
  },
  'breadcrumb-03': {
    description: 'Breadcrumb with home icon for home link only',
    file: 'breadcrumb/breadcrumb-03',
    name: 'Breadcrumb 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb']
  },
  'breadcrumb-04': {
    description: 'Breadcrumb with folders icon menu',
    file: 'breadcrumb/breadcrumb-04',
    name: 'Breadcrumb 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb', 'dropdown', 'menu']
  },
  'breadcrumb-05': {
    description: 'Breadcrumb with icons before text',
    file: 'breadcrumb/breadcrumb-05',
    name: 'Breadcrumb 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb']
  },
  'breadcrumb-06': {
    description: 'Breadcrumb with dot separators',
    file: 'breadcrumb/breadcrumb-06',
    name: 'Breadcrumb 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb']
  },
  'breadcrumb-07': {
    description: 'Breadcrumb with select dropdown',
    file: 'breadcrumb/breadcrumb-07',
    name: 'Breadcrumb 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['breadcrumb', 'select']
  },
  'breadcrumb-08': {
    description: '',
    file: 'breadcrumb/breadcrumb-08',
    name: 'Breadcrumb 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-01': {
    description: 'Default button',
    file: 'button/button-01',
    name: 'Button 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-02': {
    description: 'Outline button',
    file: 'button/button-02',
    name: 'Button 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-03': {
    description: 'Secondary button',
    file: 'button/button-03',
    name: 'Button 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-04': {
    description: 'Destructive button',
    file: 'button/button-04',
    name: 'Button 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-05': {
    description: 'Destructive outline button',
    file: 'button/button-05',
    name: 'Button 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-06': {
    description: 'Ghost button',
    file: 'button/button-06',
    name: 'Button 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-07': {
    description: 'Link button',
    file: 'button/button-07',
    name: 'Button 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-08': {
    description: 'Extra-small button',
    file: 'button/button-08',
    name: 'Button 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-09': {
    description: 'Small button',
    file: 'button/button-09',
    name: 'Button 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-10': {
    description: 'Large button',
    file: 'button/button-10',
    name: 'Button 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-11': {
    description: 'Extra-large button',
    file: 'button/button-11',
    name: 'Button 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-12': {
    description: 'Disabled button',
    file: 'button/button-12',
    name: 'Button 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'disabled']
  },
  'button-13': {
    description: 'Icon button',
    file: 'button/button-13',
    name: 'Button 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-14': {
    description: 'Small icon button',
    file: 'button/button-14',
    name: 'Button 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-15': {
    description: 'Large icon button',
    file: 'button/button-15',
    name: 'Button 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-16': {
    description: 'Button with icon',
    file: 'button/button-16',
    name: 'Button 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-17': {
    description: 'Link rendered as button',
    file: 'button/button-17',
    name: 'Button 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-18': {
    description: 'Custom loading button with manual Spinner',
    file: 'button/button-18',
    name: 'Button 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'loading']
  },
  'button-19': {
    description: 'Expandable show more/less toggle button',
    file: 'button/button-19',
    name: 'Button 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-20': {
    description: 'Back link button with chevron',
    file: 'button/button-20',
    name: 'Button 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-21': {
    description: 'Card-style button with heading and description',
    file: 'button/button-21',
    name: 'Button 21',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-22': {
    description: 'Directional pad control buttons',
    file: 'button/button-22',
    name: 'Button 22',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-23': {
    description: 'Outline like button with count',
    file: 'button/button-23',
    name: 'Button 23',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-24': {
    description: 'Social login icon buttons',
    file: 'button/button-24',
    name: 'Button 24',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-25': {
    description: '',
    file: 'button/button-25',
    name: 'Button 25',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-26': {
    description: 'Star button with count badge',
    file: 'button/button-26',
    name: 'Button 26',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-27': {
    description: 'Button group with QR code icon and sign in',
    file: 'button/button-27',
    name: 'Button 27',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'group']
  },
  'button-28': {
    description: 'Button with avatar',
    file: 'button/button-28',
    name: 'Button 28',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'avatar']
  },
  'button-29': {
    description: 'Pill-shaped button with rounded-full styling',
    file: 'button/button-29',
    name: 'Button 29',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-30': {
    description: 'Button with animated arrow on hover',
    file: 'button/button-30',
    name: 'Button 30',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-31': {
    description: 'Button with keyboard shortcut indicator',
    file: 'button/button-31',
    name: 'Button 31',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'kbd']
  },
  'button-32': {
    description: 'Button with notification badge',
    file: 'button/button-32',
    name: 'Button 32',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'badge']
  },
  'button-33': {
    description: 'Paired buttons (Cancel/Save)',
    file: 'button/button-33',
    name: 'Button 33',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-34': {
    description: 'Button with animated status dot',
    file: 'button/button-34',
    name: 'Button 34',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-35': {
    description: 'Icon-only copy button with feedback',
    file: 'button/button-35',
    name: 'Button 35',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-36': {
    description: 'Copy button with feedback',
    file: 'button/button-36',
    name: 'Button 36',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-37': {
    description: 'Rotating icon button (FAB-style toggle)',
    file: 'button/button-37',
    name: 'Button 37',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-38': {
    description: 'Social login buttons (Google, X, GitHub)',
    file: 'button/button-38',
    name: 'Button 38',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-39': {
    description: 'Hamburger menu button with animated icon',
    file: 'button/button-39',
    name: 'Button 39',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button']
  },
  'button-40': {
    description: 'Download button with progress and cancel action',
    file: 'button/button-40',
    name: 'Button 40',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'group', 'tooltip', 'toast']
  },
  'button-41': {
    description: 'Button using the built-in loading prop',
    file: 'button/button-41',
    name: 'Button 41',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'loading']
  },
  'button-42': {
    description: '',
    file: 'button/button-42',
    name: 'Button 42',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-43': {
    description: '',
    file: 'button/button-43',
    name: 'Button 43',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-44': {
    description: '',
    file: 'button/button-44',
    name: 'Button 44',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-45': {
    description: '',
    file: 'button/button-45',
    name: 'Button 45',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-46': {
    description: '',
    file: 'button/button-46',
    name: 'Button 46',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-47': {
    description: '',
    file: 'button/button-47',
    name: 'Button 47',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-48': {
    description: '',
    file: 'button/button-48',
    name: 'Button 48',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-49': {
    description: '',
    file: 'button/button-49',
    name: 'Button 49',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-50': {
    description: '',
    file: 'button/button-50',
    name: 'Button 50',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'button-51': {
    description: '',
    file: 'button/button-51',
    name: 'Button 51',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-01': {
    description: 'Basic checkbox',
    file: 'checkbox/checkbox-01',
    name: 'Checkbox 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['checkbox']
  },
  'checkbox-02': {
    description: 'Disabled checkbox',
    file: 'checkbox/checkbox-02',
    name: 'Checkbox 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['checkbox', 'disabled']
  },
  'checkbox-03': {
    description: 'Checkbox with description',
    file: 'checkbox/checkbox-03',
    name: 'Checkbox 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['checkbox']
  },
  'checkbox-04': {
    description: 'Card-style checkbox',
    file: 'checkbox/checkbox-04',
    name: 'Checkbox 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['checkbox']
  },
  'checkbox-05': {
    description: 'Checkbox form',
    file: 'checkbox/checkbox-05',
    name: 'Checkbox 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['checkbox', 'form']
  },
  'checkbox-06': {
    description: '',
    file: 'checkbox/checkbox-06',
    name: 'Checkbox 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-07': {
    description: '',
    file: 'checkbox/checkbox-07',
    name: 'Checkbox 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-08': {
    description: '',
    file: 'checkbox/checkbox-08',
    name: 'Checkbox 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-09': {
    description: '',
    file: 'checkbox/checkbox-09',
    name: 'Checkbox 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-10': {
    description: '',
    file: 'checkbox/checkbox-10',
    name: 'Checkbox 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-11': {
    description: '',
    file: 'checkbox/checkbox-11',
    name: 'Checkbox 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-12': {
    description: '',
    file: 'checkbox/checkbox-12',
    name: 'Checkbox 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-13': {
    description: '',
    file: 'checkbox/checkbox-13',
    name: 'Checkbox 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-14': {
    description: '',
    file: 'checkbox/checkbox-14',
    name: 'Checkbox 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-15': {
    description: '',
    file: 'checkbox/checkbox-15',
    name: 'Checkbox 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-16': {
    description: '',
    file: 'checkbox/checkbox-16',
    name: 'Checkbox 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-17': {
    description: '',
    file: 'checkbox/checkbox-17',
    name: 'Checkbox 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'checkbox-18': {
    description: '',
    file: 'checkbox/checkbox-18',
    name: 'Checkbox 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-01': {
    description: 'Dialog with form',
    file: 'dialog/dialog-01',
    name: 'Dialog 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['dialog']
  },
  'dialog-02': {
    description: 'Dialog opened from menu',
    file: 'dialog/dialog-02',
    name: 'Dialog 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['dialog', 'dropdown', 'menu']
  },
  'dialog-03': {
    description: 'Nested dialogs',
    file: 'dialog/dialog-03',
    name: 'Dialog 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['dialog']
  },
  'dialog-04': {
    description: 'Dialog with close confirmation',
    file: 'dialog/dialog-04',
    name: 'Dialog 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['alert dialog', 'dialog']
  },
  'dialog-05': {
    description: 'Dialog with long content',
    file: 'dialog/dialog-05',
    name: 'Dialog 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['dialog']
  },
  'dialog-06': {
    description: 'Dialog with bare footer',
    file: 'dialog/dialog-06',
    name: 'Dialog 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['dialog']
  },
  'dialog-07': {
    description: '',
    file: 'dialog/dialog-07',
    name: 'Dialog 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-08': {
    description: '',
    file: 'dialog/dialog-08',
    name: 'Dialog 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-09': {
    description: '',
    file: 'dialog/dialog-09',
    name: 'Dialog 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-10': {
    description: '',
    file: 'dialog/dialog-10',
    name: 'Dialog 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-11': {
    description: '',
    file: 'dialog/dialog-11',
    name: 'Dialog 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-12.todo': {
    description: '',
    file: 'dialog/dialog-12.todo',
    name: 'Dialog 12.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-13': {
    description: '',
    file: 'dialog/dialog-13',
    name: 'Dialog 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-14': {
    description: '',
    file: 'dialog/dialog-14',
    name: 'Dialog 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-15': {
    description: '',
    file: 'dialog/dialog-15',
    name: 'Dialog 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-16.todo': {
    description: '',
    file: 'dialog/dialog-16.todo',
    name: 'Dialog 16.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-17.todo': {
    description: '',
    file: 'dialog/dialog-17.todo',
    name: 'Dialog 17.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-18': {
    description: '',
    file: 'dialog/dialog-18',
    name: 'Dialog 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-19': {
    description: '',
    file: 'dialog/dialog-19',
    name: 'Dialog 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-20': {
    description: '',
    file: 'dialog/dialog-20',
    name: 'Dialog 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'dialog-21.todo': {
    description: '',
    file: 'dialog/dialog-21.todo',
    name: 'Dialog 21.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'empty-01': {
    description: 'Empty state with icon and actions',
    file: 'empty/empty-01',
    name: 'Empty 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['empty state']
  },
  'input-01': {
    description: 'Basic input',
    file: 'input/input-01',
    name: 'Input 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-02': {
    description: 'Small input',
    file: 'input/input-02',
    name: 'Input 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-03': {
    description: 'Large input',
    file: 'input/input-03',
    name: 'Input 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-04': {
    description: 'Disabled input',
    file: 'input/input-04',
    name: 'Input 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-05': {
    description: 'File input',
    file: 'input/input-05',
    name: 'Input 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-06': {
    description: 'Input with label',
    file: 'input/input-06',
    name: 'Input 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input', 'label']
  },
  'input-07': {
    description: 'Input with button using Group',
    file: 'input/input-07',
    name: 'Input 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'group', 'input']
  },
  'input-08': {
    description: 'Input with start text and end tooltip',
    file: 'input/input-08',
    name: 'Input 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'input', 'input group', 'popover']
  },
  'input-09': {
    description: 'Password input with toggle visibility',
    file: 'input/input-09',
    name: 'Input 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'input', 'input group', 'tooltip']
  },
  'input-10': {
    description: 'Input group mimicking a URL bar',
    file: 'input/input-10',
    name: 'Input 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'input', 'input group', 'popover']
  },
  'input-11': {
    description: 'Input group with keyboard shortcut',
    file: 'input/input-11',
    name: 'Input 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input', 'input group', 'kbd', 'search']
  },
  'input-12': {
    description: 'Input group with start loading spinner',
    file: 'input/input-12',
    name: 'Input 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input', 'input group', 'spinner', 'loading']
  },
  'input-13': {
    description: 'Input with label and required indicator',
    file: 'input/input-13',
    name: 'Input 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input', 'label']
  },
  'input-14': {
    description: 'Input with optional label',
    file: 'input/input-14',
    name: 'Input 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input', 'label']
  },
  'input-15': {
    description: 'Input with custom border and background',
    file: 'input/input-15',
    name: 'Input 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-16': {
    description: 'Input group with end loading spinner',
    file: 'input/input-16',
    name: 'Input 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input', 'input group', 'spinner', 'loading']
  },
  'input-17': {
    description: 'Read-only input',
    file: 'input/input-17',
    name: 'Input 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-18': {
    description: 'Input with characters remaining counter',
    file: 'input/input-18',
    name: 'Input 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['field', 'input']
  },
  'input-19': {
    description: 'Pill-shaped input',
    file: 'input/input-19',
    name: 'Input 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['input']
  },
  'input-20': {
    description: '',
    file: 'input/input-20',
    name: 'Input 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-21': {
    description: '',
    file: 'input/input-21',
    name: 'Input 21',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-22': {
    description: '',
    file: 'input/input-22',
    name: 'Input 22',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-23': {
    description: '',
    file: 'input/input-23',
    name: 'Input 23',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-24': {
    description: '',
    file: 'input/input-24',
    name: 'Input 24',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-25': {
    description: '',
    file: 'input/input-25',
    name: 'Input 25',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-26': {
    description: '',
    file: 'input/input-26',
    name: 'Input 26',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-27': {
    description: '',
    file: 'input/input-27',
    name: 'Input 27',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-28': {
    description: '',
    file: 'input/input-28',
    name: 'Input 28',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-29': {
    description: '',
    file: 'input/input-29',
    name: 'Input 29',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-30': {
    description: '',
    file: 'input/input-30',
    name: 'Input 30',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-31': {
    description: '',
    file: 'input/input-31',
    name: 'Input 31',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-32': {
    description: '',
    file: 'input/input-32',
    name: 'Input 32',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-33': {
    description: '',
    file: 'input/input-33',
    name: 'Input 33',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-34': {
    description: '',
    file: 'input/input-34',
    name: 'Input 34',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-35': {
    description: '',
    file: 'input/input-35',
    name: 'Input 35',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-36': {
    description: '',
    file: 'input/input-36',
    name: 'Input 36',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-37.todo': {
    description: '',
    file: 'input/input-37.todo',
    name: 'Input 37.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-38.todo': {
    description: '',
    file: 'input/input-38.todo',
    name: 'Input 38.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-39.todo': {
    description: '',
    file: 'input/input-39.todo',
    name: 'Input 39.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-40.todo': {
    description: '',
    file: 'input/input-40.todo',
    name: 'Input 40.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-41.todo': {
    description: '',
    file: 'input/input-41.todo',
    name: 'Input 41.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-42': {
    description: '',
    file: 'input/input-42',
    name: 'Input 42',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-43': {
    description: '',
    file: 'input/input-43',
    name: 'Input 43',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-44': {
    description: '',
    file: 'input/input-44',
    name: 'Input 44',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-45': {
    description: '',
    file: 'input/input-45',
    name: 'Input 45',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-46': {
    description: '',
    file: 'input/input-46',
    name: 'Input 46',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-47.todo': {
    description: '',
    file: 'input/input-47.todo',
    name: 'Input 47.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-48.todo': {
    description: '',
    file: 'input/input-48.todo',
    name: 'Input 48.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-49.todo': {
    description: '',
    file: 'input/input-49.todo',
    name: 'Input 49.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-50.todo': {
    description: '',
    file: 'input/input-50.todo',
    name: 'Input 50.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-51': {
    description: '',
    file: 'input/input-51',
    name: 'Input 51',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-52': {
    description: '',
    file: 'input/input-52',
    name: 'Input 52',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-53': {
    description: '',
    file: 'input/input-53',
    name: 'Input 53',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-54': {
    description: '',
    file: 'input/input-54',
    name: 'Input 54',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-55': {
    description: '',
    file: 'input/input-55',
    name: 'Input 55',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-56': {
    description: '',
    file: 'input/input-56',
    name: 'Input 56',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-57.todo': {
    description: '',
    file: 'input/input-57.todo',
    name: 'Input 57.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-58.todo': {
    description: '',
    file: 'input/input-58.todo',
    name: 'Input 58.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'input-59.todo': {
    description: '',
    file: 'input/input-59.todo',
    name: 'Input 59.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-01': {
    description: '',
    file: 'notification/notification-01',
    name: 'Notification 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-02': {
    description: '',
    file: 'notification/notification-02',
    name: 'Notification 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-03': {
    description: '',
    file: 'notification/notification-03',
    name: 'Notification 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-04': {
    description: '',
    file: 'notification/notification-04',
    name: 'Notification 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-05': {
    description: '',
    file: 'notification/notification-05',
    name: 'Notification 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-06': {
    description: '',
    file: 'notification/notification-06',
    name: 'Notification 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-07': {
    description: '',
    file: 'notification/notification-07',
    name: 'Notification 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-08': {
    description: '',
    file: 'notification/notification-08',
    name: 'Notification 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-09': {
    description: '',
    file: 'notification/notification-09',
    name: 'Notification 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-10': {
    description: '',
    file: 'notification/notification-10',
    name: 'Notification 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-11': {
    description: '',
    file: 'notification/notification-11',
    name: 'Notification 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-12': {
    description: '',
    file: 'notification/notification-12',
    name: 'Notification 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-13': {
    description: '',
    file: 'notification/notification-13',
    name: 'Notification 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-14': {
    description: '',
    file: 'notification/notification-14',
    name: 'Notification 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-15': {
    description: '',
    file: 'notification/notification-15',
    name: 'Notification 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-16': {
    description: '',
    file: 'notification/notification-16',
    name: 'Notification 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-17': {
    description: '',
    file: 'notification/notification-17',
    name: 'Notification 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-18': {
    description: '',
    file: 'notification/notification-18',
    name: 'Notification 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-19.todo': {
    description: '',
    file: 'notification/notification-19.todo',
    name: 'Notification 19.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-20.todo': {
    description: '',
    file: 'notification/notification-20.todo',
    name: 'Notification 20.todo',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-21': {
    description: '',
    file: 'notification/notification-21',
    name: 'Notification 21',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-22': {
    description: '',
    file: 'notification/notification-22',
    name: 'Notification 22',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'notification-23': {
    description: '',
    file: 'notification/notification-23',
    name: 'Notification 23',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-01': {
    description: 'Pagination example',
    file: 'pagination/pagination-01',
    name: 'Pagination 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['pagination']
  },
  'pagination-02': {
    description: 'Pagination with previous and next buttons only',
    file: 'pagination/pagination-02',
    name: 'Pagination 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['pagination']
  },
  'pagination-03': {
    description: 'Pagination with select, and previous and next buttons',
    file: 'pagination/pagination-03',
    name: 'Pagination 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['pagination', 'select']
  },
  'pagination-04': {
    description: '',
    file: 'pagination/pagination-04',
    name: 'Pagination 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-05': {
    description: '',
    file: 'pagination/pagination-05',
    name: 'Pagination 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-06': {
    description: '',
    file: 'pagination/pagination-06',
    name: 'Pagination 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-07': {
    description: '',
    file: 'pagination/pagination-07',
    name: 'Pagination 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-08': {
    description: '',
    file: 'pagination/pagination-08',
    name: 'Pagination 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-09': {
    description: '',
    file: 'pagination/pagination-09',
    name: 'Pagination 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-10': {
    description: '',
    file: 'pagination/pagination-10',
    name: 'Pagination 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-11': {
    description: '',
    file: 'pagination/pagination-11',
    name: 'Pagination 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'pagination-12': {
    description: '',
    file: 'pagination/pagination-12',
    name: 'Pagination 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'popover-01': {
    description: 'Popover with a form',
    file: 'popover/popover-01',
    name: 'Popover 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'field', 'form', 'popover', 'textarea']
  },
  'popover-02': {
    description: 'Popover with close button',
    file: 'popover/popover-02',
    name: 'Popover 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'popover']
  },
  'popover-03': {
    description: 'Animated popovers',
    file: 'popover/popover-03',
    name: 'Popover 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['avatar', 'button', 'popover']
  },
  'popover-04': {
    description: '',
    file: 'popover/popover-04',
    name: 'Popover 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'popover-05': {
    description: '',
    file: 'popover/popover-05',
    name: 'Popover 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'popover-06': {
    description: '',
    file: 'popover/popover-06',
    name: 'Popover 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'popover-07': {
    description: '',
    file: 'popover/popover-07',
    name: 'Popover 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'popover-08': {
    description: '',
    file: 'popover/popover-08',
    name: 'Popover 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'popover-09': {
    description: '',
    file: 'popover/popover-09',
    name: 'Popover 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-01': {
    description: '',
    file: 'radio/radio-01',
    name: 'Radio 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-02': {
    description: '',
    file: 'radio/radio-02',
    name: 'Radio 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-03': {
    description: '',
    file: 'radio/radio-03',
    name: 'Radio 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-04': {
    description: '',
    file: 'radio/radio-04',
    name: 'Radio 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-05': {
    description: '',
    file: 'radio/radio-05',
    name: 'Radio 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-06': {
    description: '',
    file: 'radio/radio-06',
    name: 'Radio 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-07': {
    description: '',
    file: 'radio/radio-07',
    name: 'Radio 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-08': {
    description: '',
    file: 'radio/radio-08',
    name: 'Radio 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-09': {
    description: '',
    file: 'radio/radio-09',
    name: 'Radio 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-10': {
    description: '',
    file: 'radio/radio-10',
    name: 'Radio 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-11': {
    description: '',
    file: 'radio/radio-11',
    name: 'Radio 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-12': {
    description: '',
    file: 'radio/radio-12',
    name: 'Radio 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-13': {
    description: '',
    file: 'radio/radio-13',
    name: 'Radio 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-14': {
    description: '',
    file: 'radio/radio-14',
    name: 'Radio 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-15': {
    description: '',
    file: 'radio/radio-15',
    name: 'Radio 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-16': {
    description: '',
    file: 'radio/radio-16',
    name: 'Radio 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-17': {
    description: '',
    file: 'radio/radio-17',
    name: 'Radio 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-18': {
    description: '',
    file: 'radio/radio-18',
    name: 'Radio 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'radio-19': {
    description: '',
    file: 'radio/radio-19',
    name: 'Radio 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-01': {
    description: 'Basic select',
    file: 'select/select-01',
    name: 'Select 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-02': {
    description: 'Small select',
    file: 'select/select-02',
    name: 'Select 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-03': {
    description: 'Large select',
    file: 'select/select-03',
    name: 'Select 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-05': {
    description: 'Select without item alignment',
    file: 'select/select-05',
    name: 'Select 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-15': {
    description: 'Pill-shaped select trigger',
    file: 'select/select-15',
    name: 'Select 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-16': {
    description: 'Select with left text label',
    file: 'select/select-16',
    name: 'Select 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-17': {
    description: 'Select with country flags',
    file: 'select/select-17',
    name: 'Select 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-18': {
    description: 'Select with description in options only',
    file: 'select/select-18',
    name: 'Select 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-19': {
    description: 'Select with avatars',
    file: 'select/select-19',
    name: 'Select 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select', 'avatar']
  },
  'select-20': {
    description: 'Rich select with avatars and usernames',
    file: 'select/select-20',
    name: 'Select 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select', 'avatar']
  },
  'select-21': {
    description: 'Auto width select',
    file: 'select/select-21',
    name: 'Select 21',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-22': {
    description: 'Select with custom border and background',
    file: 'select/select-22',
    name: 'Select 22',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-23': {
    description: 'Select with label',
    file: 'select/select-23',
    name: 'Select 23',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['select']
  },
  'select-24': {
    description: '',
    file: 'select/select-24',
    name: 'Select 24',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-25': {
    description: '',
    file: 'select/select-25',
    name: 'Select 25',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-26': {
    description: '',
    file: 'select/select-26',
    name: 'Select 26',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-27': {
    description: '',
    file: 'select/select-27',
    name: 'Select 27',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-28': {
    description: '',
    file: 'select/select-28',
    name: 'Select 28',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-29': {
    description: '',
    file: 'select/select-29',
    name: 'Select 29',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-30': {
    description: '',
    file: 'select/select-30',
    name: 'Select 30',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-31': {
    description: '',
    file: 'select/select-31',
    name: 'Select 31',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-32': {
    description: '',
    file: 'select/select-32',
    name: 'Select 32',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-33': {
    description: '',
    file: 'select/select-33',
    name: 'Select 33',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-34': {
    description: '',
    file: 'select/select-34',
    name: 'Select 34',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-35': {
    description: '',
    file: 'select/select-35',
    name: 'Select 35',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-36': {
    description: '',
    file: 'select/select-36',
    name: 'Select 36',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-37': {
    description: '',
    file: 'select/select-37',
    name: 'Select 37',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-38': {
    description: '',
    file: 'select/select-38',
    name: 'Select 38',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-39': {
    description: '',
    file: 'select/select-39',
    name: 'Select 39',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-40': {
    description: '',
    file: 'select/select-40',
    name: 'Select 40',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-41': {
    description: '',
    file: 'select/select-41',
    name: 'Select 41',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-42': {
    description: '',
    file: 'select/select-42',
    name: 'Select 42',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-43': {
    description: '',
    file: 'select/select-43',
    name: 'Select 43',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-44': {
    description: '',
    file: 'select/select-44',
    name: 'Select 44',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'select-45': {
    description: '',
    file: 'select/select-45',
    name: 'Select 45',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'slider-01': {
    description: 'Basic slider',
    file: 'slider/slider-01',
    name: 'Slider 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-02': {
    description: 'Slider with label and value',
    file: 'slider/slider-02',
    name: 'Slider 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-03': {
    description: 'Disabled slider',
    file: 'slider/slider-03',
    name: 'Slider 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'disabled']
  },
  'slider-04': {
    description: 'Slider with reference labels',
    file: 'slider/slider-04',
    name: 'Slider 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-05': {
    description: 'Slider with ticks',
    file: 'slider/slider-05',
    name: 'Slider 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-06': {
    description: 'Slider with labels above',
    file: 'slider/slider-06',
    name: 'Slider 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-07': {
    description: 'Range slider',
    file: 'slider/slider-07',
    name: 'Slider 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-08': {
    description: 'Slider with 3 thumbs',
    file: 'slider/slider-08',
    name: 'Slider 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-09': {
    description: 'Range slider with collision behavior none',
    file: 'slider/slider-09',
    name: 'Slider 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-10': {
    description: 'Range slider with collision behavior swap',
    file: 'slider/slider-10',
    name: 'Slider 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-11': {
    description: 'Slider with icons',
    file: 'slider/slider-11',
    name: 'Slider 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-12': {
    description: 'Slider with input',
    file: 'slider/slider-12',
    name: 'Slider 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'number field']
  },
  'slider-13': {
    description: 'Range slider with inputs',
    file: 'slider/slider-13',
    name: 'Slider 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'number field']
  },
  'slider-14': {
    description: 'Slider with increment and decrement buttons',
    file: 'slider/slider-14',
    name: 'Slider 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'button']
  },
  'slider-15': {
    description: 'Price range slider',
    file: 'slider/slider-15',
    name: 'Slider 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-16': {
    description: 'Emoji rating slider',
    file: 'slider/slider-16',
    name: 'Slider 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-17': {
    description: 'Vertical slider',
    file: 'slider/slider-17',
    name: 'Slider 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-18': {
    description: 'Vertical range slider',
    file: 'slider/slider-18',
    name: 'Slider 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-19': {
    description: 'Vertical slider with input',
    file: 'slider/slider-19',
    name: 'Slider 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'number field']
  },
  'slider-20': {
    description: 'Equalizer with vertical sliders',
    file: 'slider/slider-20',
    name: 'Slider 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider']
  },
  'slider-21': {
    description: 'Object position sliders with reset',
    file: 'slider/slider-21',
    name: 'Slider 21',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'number field', 'button']
  },
  'slider-22': {
    description: 'Price slider with histogram',
    file: 'slider/slider-22',
    name: 'Slider 22',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'number field', 'input group', 'button', 'filter']
  },
  'slider-23': {
    description: 'Slider in form',
    file: 'slider/slider-23',
    name: 'Slider 23',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['slider', 'form']
  },
  'slider-24': {
    description: '',
    file: 'slider/slider-24',
    name: 'Slider 24',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'slider-25': {
    description: '',
    file: 'slider/slider-25',
    name: 'Slider 25',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'slider-26': {
    description: '',
    file: 'slider/slider-26',
    name: 'Slider 26',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'slider-27': {
    description: '',
    file: 'slider/slider-27',
    name: 'Slider 27',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-01': {
    description: 'Basic switch',
    file: 'switch/switch-01',
    name: 'Switch 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['switch']
  },
  'switch-02': {
    description: 'Disabled switch',
    file: 'switch/switch-02',
    name: 'Switch 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['switch']
  },
  'switch-03': {
    description: 'Switch with description',
    file: 'switch/switch-03',
    name: 'Switch 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['switch']
  },
  'switch-04': {
    description: 'Switch card',
    file: 'switch/switch-04',
    name: 'Switch 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['switch']
  },
  'switch-05': {
    description: 'Switch in form',
    file: 'switch/switch-05',
    name: 'Switch 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['switch']
  },
  'switch-06': {
    description: 'Custom size switch',
    file: 'switch/switch-06',
    name: 'Switch 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['switch']
  },
  'switch-07': {
    description: '',
    file: 'switch/switch-07',
    name: 'Switch 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-08': {
    description: '',
    file: 'switch/switch-08',
    name: 'Switch 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-09': {
    description: '',
    file: 'switch/switch-09',
    name: 'Switch 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-10': {
    description: '',
    file: 'switch/switch-10',
    name: 'Switch 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-11': {
    description: '',
    file: 'switch/switch-11',
    name: 'Switch 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-12': {
    description: '',
    file: 'switch/switch-12',
    name: 'Switch 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-13': {
    description: '',
    file: 'switch/switch-13',
    name: 'Switch 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-14': {
    description: '',
    file: 'switch/switch-14',
    name: 'Switch 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-15': {
    description: '',
    file: 'switch/switch-15',
    name: 'Switch 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-16': {
    description: '',
    file: 'switch/switch-16',
    name: 'Switch 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'switch-17': {
    description: '',
    file: 'switch/switch-17',
    name: 'Switch 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-01': {
    description: '',
    file: 'tab/tab-01',
    name: 'Tab 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-02': {
    description: '',
    file: 'tab/tab-02',
    name: 'Tab 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-03': {
    description: '',
    file: 'tab/tab-03',
    name: 'Tab 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-04': {
    description: '',
    file: 'tab/tab-04',
    name: 'Tab 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-05': {
    description: '',
    file: 'tab/tab-05',
    name: 'Tab 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-06': {
    description: '',
    file: 'tab/tab-06',
    name: 'Tab 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-07': {
    description: '',
    file: 'tab/tab-07',
    name: 'Tab 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-08': {
    description: '',
    file: 'tab/tab-08',
    name: 'Tab 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-09': {
    description: '',
    file: 'tab/tab-09',
    name: 'Tab 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-10': {
    description: '',
    file: 'tab/tab-10',
    name: 'Tab 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-11': {
    description: '',
    file: 'tab/tab-11',
    name: 'Tab 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-12': {
    description: '',
    file: 'tab/tab-12',
    name: 'Tab 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-13': {
    description: '',
    file: 'tab/tab-13',
    name: 'Tab 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-14': {
    description: '',
    file: 'tab/tab-14',
    name: 'Tab 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-15': {
    description: '',
    file: 'tab/tab-15',
    name: 'Tab 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-16': {
    description: '',
    file: 'tab/tab-16',
    name: 'Tab 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-17': {
    description: '',
    file: 'tab/tab-17',
    name: 'Tab 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-18': {
    description: '',
    file: 'tab/tab-18',
    name: 'Tab 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-19': {
    description: '',
    file: 'tab/tab-19',
    name: 'Tab 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tab-20': {
    description: '',
    file: 'tab/tab-20',
    name: 'Tab 20',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'textarea-01': {
    description: 'Basic textarea',
    file: 'textarea/textarea-01',
    name: 'Textarea 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-02': {
    description: 'Small textarea',
    file: 'textarea/textarea-02',
    name: 'Textarea 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-03': {
    description: 'Large textarea',
    file: 'textarea/textarea-03',
    name: 'Textarea 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-04': {
    description: 'Disabled textarea',
    file: 'textarea/textarea-04',
    name: 'Textarea 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-05': {
    description: 'Textarea with label',
    file: 'textarea/textarea-05',
    name: 'Textarea 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-06': {
    description: 'Textarea in form',
    file: 'textarea/textarea-06',
    name: 'Textarea 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-07': {
    description: 'Textarea with label and required indicator',
    file: 'textarea/textarea-07',
    name: 'Textarea 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['label', 'textarea']
  },
  'textarea-08': {
    description: 'Textarea with optional label',
    file: 'textarea/textarea-08',
    name: 'Textarea 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['label', 'textarea']
  },
  'textarea-09': {
    description: 'Textarea with custom border and background',
    file: 'textarea/textarea-09',
    name: 'Textarea 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-10': {
    description: 'Read-only textarea',
    file: 'textarea/textarea-10',
    name: 'Textarea 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-11': {
    description: 'Textarea with characters remaining counter',
    file: 'textarea/textarea-11',
    name: 'Textarea 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['field', 'textarea']
  },
  'textarea-12': {
    description: 'Textarea field with required indicator',
    file: 'textarea/textarea-12',
    name: 'Textarea 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['field', 'label', 'textarea']
  },
  'textarea-13': {
    description: 'Shorter textarea with fixed height',
    file: 'textarea/textarea-13',
    name: 'Textarea 13',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['textarea']
  },
  'textarea-14': {
    description: 'Textarea with button aligned right',
    file: 'textarea/textarea-14',
    name: 'Textarea 14',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'textarea']
  },
  'textarea-15': {
    description: 'Textarea with button aligned left',
    file: 'textarea/textarea-15',
    name: 'Textarea 15',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['button', 'textarea']
  },
  'textarea-16': {
    description: '',
    file: 'textarea/textarea-16',
    name: 'Textarea 16',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'textarea-17': {
    description: '',
    file: 'textarea/textarea-17',
    name: 'Textarea 17',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'textarea-18': {
    description: '',
    file: 'textarea/textarea-18',
    name: 'Textarea 18',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'textarea-19': {
    description: '',
    file: 'textarea/textarea-19',
    name: 'Textarea 19',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-01': {
    description: '',
    file: 'timeline/timeline-01',
    name: 'Timeline 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-02': {
    description: '',
    file: 'timeline/timeline-02',
    name: 'Timeline 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-03': {
    description: '',
    file: 'timeline/timeline-03',
    name: 'Timeline 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-04': {
    description: '',
    file: 'timeline/timeline-04',
    name: 'Timeline 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-05': {
    description: '',
    file: 'timeline/timeline-05',
    name: 'Timeline 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-06': {
    description: '',
    file: 'timeline/timeline-06',
    name: 'Timeline 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-07': {
    description: '',
    file: 'timeline/timeline-07',
    name: 'Timeline 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-08': {
    description: '',
    file: 'timeline/timeline-08',
    name: 'Timeline 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-09': {
    description: '',
    file: 'timeline/timeline-09',
    name: 'Timeline 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-10': {
    description: '',
    file: 'timeline/timeline-10',
    name: 'Timeline 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-11': {
    description: '',
    file: 'timeline/timeline-11',
    name: 'Timeline 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'timeline-12': {
    description: '',
    file: 'timeline/timeline-12',
    name: 'Timeline 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-01': {
    description: 'Basic tooltip',
    file: 'tooltip/tooltip-01',
    name: 'Tooltip 01',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['tooltip']
  },
  'tooltip-02': {
    description: 'Grouped tooltips',
    file: 'tooltip/tooltip-02',
    name: 'Tooltip 02',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['tooltip']
  },
  'tooltip-03': {
    description: 'Toggle group animated tooltip',
    file: 'tooltip/tooltip-03',
    name: 'Tooltip 03',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['tooltip']
  },
  'tooltip-04': {
    description: 'Vertical group with animated tooltip',
    file: 'tooltip/tooltip-04',
    name: 'Tooltip 04',
    npmDependencies: [],
    registryDependencies: [],
    tags: ['tooltip']
  },
  'tooltip-05': {
    description: '',
    file: 'tooltip/tooltip-05',
    name: 'Tooltip 05',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-06': {
    description: '',
    file: 'tooltip/tooltip-06',
    name: 'Tooltip 06',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-07': {
    description: '',
    file: 'tooltip/tooltip-07',
    name: 'Tooltip 07',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-08': {
    description: '',
    file: 'tooltip/tooltip-08',
    name: 'Tooltip 08',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-09': {
    description: '',
    file: 'tooltip/tooltip-09',
    name: 'Tooltip 09',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-10': {
    description: '',
    file: 'tooltip/tooltip-10',
    name: 'Tooltip 10',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-11': {
    description: '',
    file: 'tooltip/tooltip-11',
    name: 'Tooltip 11',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  },
  'tooltip-12': {
    description: '',
    file: 'tooltip/tooltip-12',
    name: 'Tooltip 12',
    npmDependencies: [],
    registryDependencies: [],
    tags: []
  }
};

export { particles };
