/**
 * This file is auto-generated by scripts/createUiRegistry.ts
 * Do not edit this file directly.
 * To update, edit the source files in scripts/user-registry-ui-metadata.ts and run: pnpm generate:registry
 * @version 0.1.0
 * !!!!!!!!!!
 */
export interface RegistryUIEntry {
  category: 'ui' | 'origin-ui' | 'bits-ui' | 'extra'; // for now, just a simple category to separate "core" UI components from extra ones
  description: string;
  folder: string; // relative to src/lib/components/ui/
  isnew: boolean; // whether this is a new component that should be highlighted in the UI
  name: string;
  npmDependencies: string[];
  registryDependencies: string[];
}

export type RegistryUiData = Record<string, RegistryUIEntry>;
const allComponents: RegistryUiData = {
  accordion: {
    category: 'ui',
    description: 'A set of collapsible panels with headings and content.',
    folder: 'accordion',
    isnew: false,
    name: 'Accordion',
    npmDependencies: [],
    registryDependencies: []
  },
  alert: {
    category: 'ui',
    description: 'A callout for displaying important information.',
    folder: 'alert',
    isnew: false,
    name: 'Alert',
    npmDependencies: [],
    registryDependencies: []
  },
  'alert-dialog': {
    category: 'ui',
    description: 'A dialog that requires user response to proceed.',
    folder: 'alert-dialog',
    isnew: false,
    name: 'Alert Dialog',
    npmDependencies: [],
    registryDependencies: []
  },
  'aspect-ratio': {
    category: 'bits-ui',
    description: 'Displays content within a desired ratio.',
    folder: 'aspect-ratio',
    isnew: false,
    name: 'Aspect Ratio',
    npmDependencies: [],
    registryDependencies: []
  },
  autocomplete: {
    category: 'ui',
    description: 'An input that suggests options as you type.',
    folder: 'autocomplete',
    isnew: false,
    name: 'Autocomplete',
    npmDependencies: [],
    registryDependencies: []
  },
  avatar: {
    category: 'ui',
    description: 'An image element with a fallback for representing the user.',
    folder: 'avatar',
    isnew: false,
    name: 'Avatar',
    npmDependencies: [],
    registryDependencies: []
  },
  badge: {
    category: 'ui',
    description: 'A badge or a component that looks like a badge.',
    folder: 'badge',
    isnew: false,
    name: 'Badge',
    npmDependencies: [],
    registryDependencies: []
  },
  breadcrumb: {
    category: 'ui',
    description: 'Displays the path to the current resource using a hierarchy of links.',
    folder: 'breadcrumb',
    isnew: false,
    name: 'Breadcrumb',
    npmDependencies: [],
    registryDependencies: []
  },
  button: {
    category: 'ui',
    description: 'A button or a component that looks like a button.',
    folder: 'button',
    isnew: false,
    name: 'Button',
    npmDependencies: [],
    registryDependencies: []
  },
  card: {
    category: 'ui',
    description: 'A content container for grouping related information.',
    folder: 'card',
    isnew: false,
    name: 'Card',
    npmDependencies: [],
    registryDependencies: []
  },
  checkbox: {
    category: 'ui',
    description: 'A control allowing the user to toggle between checked and not checked.',
    folder: 'checkbox',
    isnew: false,
    name: 'Checkbox',
    npmDependencies: [],
    registryDependencies: []
  },
  'checkbox-group': {
    category: 'ui',
    description: 'Provides shared state to a series of checkboxes.',
    folder: 'checkbox-group',
    isnew: false,
    name: 'Checkbox Group',
    npmDependencies: [],
    registryDependencies: []
  },
  collapsible: {
    category: 'ui',
    description: 'A collapsible panel controlled by a button trigger.',
    folder: 'collapsible',
    isnew: false,
    name: 'Collapsible',
    npmDependencies: [],
    registryDependencies: []
  },
  combobox: {
    category: 'ui',
    description: 'An input combined with a list of predefined items to select.',
    folder: 'combobox',
    isnew: false,
    name: 'Combobox',
    npmDependencies: [],
    registryDependencies: []
  },
  command: {
    category: 'ui',
    description:
      'A command palette component built with Dialog and Autocomplete for searching and executing commands.',
    folder: 'command',
    isnew: false,
    name: 'Command',
    npmDependencies: [],
    registryDependencies: []
  },
  'context-menu': {
    category: 'ui',
    description: 'A menu that opens on right-click, providing contextual actions.',
    folder: 'context-menu',
    isnew: true,
    name: 'Context Menu',
    npmDependencies: [],
    registryDependencies: []
  },
  cropper: {
    category: 'origin-ui',
    description: 'A component for cropping images with a resizable and movable selection area.',
    folder: 'cropper',
    isnew: false,
    name: 'Cropper',
    npmDependencies: [],
    registryDependencies: []
  },
  dialog: {
    category: 'ui',
    description: 'A popup that opens on top of the entire page.',
    folder: 'dialog',
    isnew: false,
    name: 'Dialog',
    npmDependencies: [],
    registryDependencies: []
  },
  drawer: {
    category: 'ui',
    description:
      'A panel that slides in from the edge of the screen with swipe gestures, snap points, and nested drawer support.',
    folder: 'drawer',
    isnew: true,
    name: 'Drawer',
    npmDependencies: [],
    registryDependencies: []
  },
  empty: {
    category: 'ui',
    description: 'A container for displaying empty state information.',
    folder: 'empty',
    isnew: false,
    name: 'Empty',
    npmDependencies: [],
    registryDependencies: []
  },
  field: {
    category: 'ui',
    description: 'A component that provides labelling and validation for form controls.',
    folder: 'field',
    isnew: false,
    name: 'Field',
    npmDependencies: [],
    registryDependencies: []
  },
  fieldset: {
    category: 'ui',
    description: 'A native fieldset element with a legend.',
    folder: 'fieldset',
    isnew: false,
    name: 'Fieldset',
    npmDependencies: [],
    registryDependencies: []
  },
  'file-upload': {
    category: 'origin-ui',
    description: 'A component for uploading files with drag-and-drop support.',
    folder: 'file-upload',
    isnew: false,
    name: 'File Upload',
    npmDependencies: [],
    registryDependencies: []
  },
  form: {
    category: 'ui',
    description: 'A form wrapper component that simplifies validation and submission.',
    folder: 'form',
    isnew: false,
    name: 'Form',
    npmDependencies: [],
    registryDependencies: []
  },
  frame: {
    category: 'ui',
    description: 'A framed container for grouping related information.',
    folder: 'frame',
    isnew: false,
    name: 'Frame',
    npmDependencies: [],
    registryDependencies: []
  },
  group: {
    category: 'ui',
    description: 'A component for visually grouping a series of controls.',
    folder: 'group',
    isnew: false,
    name: 'Group',
    npmDependencies: [],
    registryDependencies: []
  },
  input: {
    category: 'ui',
    description: 'A native input element.',
    folder: 'input',
    isnew: false,
    name: 'Input',
    npmDependencies: [],
    registryDependencies: []
  },
  'input-group': {
    category: 'ui',
    description:
      'A flexible component for grouping inputs with addons, buttons, and other elements.',
    folder: 'input-group',
    isnew: false,
    name: 'Input Group',
    npmDependencies: [],
    registryDependencies: []
  },
  kbd: {
    category: 'ui',
    description: 'A component for displaying keyboard keys and shortcuts.',
    folder: 'kbd',
    isnew: false,
    name: 'Kbd',
    npmDependencies: [],
    registryDependencies: []
  },
  label: {
    category: 'ui',
    description: 'Renders an accessible label associated with controls.',
    folder: 'label',
    isnew: false,
    name: 'Label',
    npmDependencies: [],
    registryDependencies: []
  },
  'link-preview': {
    category: 'bits-ui',
    description: 'A popup that appears when an element is hovered, showing preview information.',
    folder: 'link-preview',
    isnew: false,
    name: 'Link Preview',
    npmDependencies: [],
    registryDependencies: []
  },
  menu: {
    category: 'ui',
    description: 'A list of actions in a dropdown, enhanced with keyboard navigation.',
    folder: 'menu',
    isnew: true,
    name: 'Menu',
    npmDependencies: [],
    registryDependencies: []
  },
  meter: {
    category: 'ui',
    description: 'A graphical display of a numeric value within a range.',
    folder: 'meter',
    isnew: false,
    name: 'Meter',
    npmDependencies: [],
    registryDependencies: []
  },
  'number-field': {
    category: 'ui',
    description: 'A numeric input element with increment and decrement buttons, and a scrub area.',
    folder: 'number-field',
    isnew: false,
    name: 'Number Field',
    npmDependencies: [],
    registryDependencies: []
  },
  'otp-field': {
    category: 'ui',
    description: 'A segmented input for one-time passwords and verification codes.',
    folder: 'otp-field',
    isnew: true,
    name: 'Otp Field',
    npmDependencies: [],
    registryDependencies: []
  },
  pagination: {
    category: 'ui',
    description: 'A pagination with page navigation, next and previous links.',
    folder: 'pagination',
    isnew: false,
    name: 'Pagination',
    npmDependencies: [],
    registryDependencies: []
  },
  popover: {
    category: 'ui',
    description: 'An accessible popup anchored to a button.',
    folder: 'popover',
    isnew: false,
    name: 'Popover',
    npmDependencies: [],
    registryDependencies: []
  },
  'preview-card': {
    category: 'ui',
    description:
      'A popup that appears when a link is hovered, showing a preview for sighted users.',
    folder: 'preview-card',
    isnew: false,
    name: 'Preview Card',
    npmDependencies: [],
    registryDependencies: []
  },
  progress: {
    category: 'ui',
    description: 'Displays the status of a task that takes a long time.',
    folder: 'progress',
    isnew: false,
    name: 'Progress',
    npmDependencies: [],
    registryDependencies: []
  },
  'radio-group': {
    category: 'ui',
    description:
      'A set of checkable buttons where no more than one of the buttons can be checked at a time.',
    folder: 'radio-group',
    isnew: false,
    name: 'Radio Group',
    npmDependencies: [],
    registryDependencies: []
  },
  'scroll-area': {
    category: 'ui',
    description: 'A native scroll container with custom scrollbars.',
    folder: 'scroll-area',
    isnew: false,
    name: 'Scroll Area',
    npmDependencies: [],
    registryDependencies: []
  },
  select: {
    category: 'ui',
    description: 'A common form component for choosing a predefined value in a dropdown menu.',
    folder: 'select',
    isnew: false,
    name: 'Select',
    npmDependencies: [],
    registryDependencies: []
  },
  separator: {
    category: 'ui',
    description: 'A separator element accessible to screen readers.',
    folder: 'separator',
    isnew: false,
    name: 'Separator',
    npmDependencies: [],
    registryDependencies: []
  },
  sheet: {
    category: 'ui',
    description: 'A flyout that opens from the side of the screen, based on the dialog component.',
    folder: 'sheet',
    isnew: false,
    name: 'Sheet',
    npmDependencies: [],
    registryDependencies: []
  },
  skeleton: {
    category: 'ui',
    description: 'A loading state skeleton for your components.',
    folder: 'skeleton',
    isnew: false,
    name: 'Skeleton',
    npmDependencies: [],
    registryDependencies: []
  },
  slider: {
    category: 'ui',
    description: 'An input where the user selects a value from within a given range.',
    folder: 'slider',
    isnew: false,
    name: 'Slider',
    npmDependencies: [],
    registryDependencies: []
  },
  spinner: {
    category: 'ui',
    description: 'An indicator that can be used to show a loading state.',
    folder: 'spinner',
    isnew: false,
    name: 'Spinner',
    npmDependencies: [],
    registryDependencies: []
  },
  'split-pane': {
    category: 'extra',
    description: 'A component to layout resizable panels with a draggable divider.',
    folder: 'split-pane',
    isnew: false,
    name: 'Split Pane',
    npmDependencies: [],
    registryDependencies: []
  },
  stepper: {
    category: 'origin-ui',
    description: 'A component for displaying a series of steps in a process.',
    folder: 'stepper',
    isnew: false,
    name: 'Stepper',
    npmDependencies: [],
    registryDependencies: []
  },
  switch: {
    category: 'ui',
    description: 'A control that indicates whether a setting is on or off.',
    folder: 'switch',
    isnew: false,
    name: 'Switch',
    npmDependencies: [],
    registryDependencies: []
  },
  table: {
    category: 'ui',
    description: 'A simple table component for displaying tabular data.',
    folder: 'table',
    isnew: false,
    name: 'Table',
    npmDependencies: [],
    registryDependencies: []
  },
  tabs: {
    category: 'ui',
    description: 'A component for toggling between related panels on the same page.',
    folder: 'tabs',
    isnew: false,
    name: 'Tabs',
    npmDependencies: [],
    registryDependencies: []
  },
  textarea: {
    category: 'ui',
    description: 'A native textarea element for multi-line text input.',
    folder: 'textarea',
    isnew: false,
    name: 'Textarea',
    npmDependencies: [],
    registryDependencies: []
  },
  timeline: {
    category: 'origin-ui',
    description: 'A component for displaying a series of events in chronological order.',
    folder: 'timeline',
    isnew: false,
    name: 'Timeline',
    npmDependencies: [],
    registryDependencies: []
  },
  toast: {
    category: 'ui',
    description: 'A temporary notification that appears on screen to inform users.',
    folder: 'toast',
    isnew: false,
    name: 'Toast',
    npmDependencies: [],
    registryDependencies: []
  },
  toggle: {
    category: 'ui',
    description: 'A two-state button that can be toggled on or off.',
    folder: 'toggle',
    isnew: false,
    name: 'Toggle',
    npmDependencies: [],
    registryDependencies: []
  },
  'toggle-group': {
    category: 'ui',
    description: 'Provides a shared state to a series of toggle buttons.',
    folder: 'toggle-group',
    isnew: false,
    name: 'Toggle Group',
    npmDependencies: [],
    registryDependencies: []
  },
  toolbar: {
    category: 'ui',
    description: 'A container for grouping a set of buttons and controls.',
    folder: 'toolbar',
    isnew: false,
    name: 'Toolbar',
    npmDependencies: [],
    registryDependencies: []
  },
  tooltip: {
    category: 'ui',
    description:
      'A popup that appears when an element is hovered or focused, showing a hint for sighted users.',
    folder: 'tooltip',
    isnew: false,
    name: 'Tooltip',
    npmDependencies: [],
    registryDependencies: []
  },
  tree: {
    category: 'origin-ui',
    description: 'A component for displaying a hierarchical tree of items.',
    folder: 'tree',
    isnew: true,
    name: 'Tree',
    npmDependencies: [],
    registryDependencies: []
  }
};

export { allComponents };
