/* eslint-disable */
/**
 * !!!!!!!!!!
 * This file is auto-generated. Do not edit manually
 * Last generated at: 5/16/2026, 10:54:31 PM
 * To update, run: pnpm generate:registry --format
 * @version 0.1.0
 * !!!!!!!!!!
 */
export const COSSUI_DIRECTORIES = {
  ACCORDION: {
    directory: "accordion",
    description: "A set of collapsible panels with headings and content.",
    isnew: false,
    category: "ui",
    name: "Accordion",
    components: [
      "accordion-01.svelte",
      "accordion-02.svelte",
      "accordion-03.svelte",
      "accordion-04.svelte",
      "accordion-05.svelte",
      "accordion-06.svelte",
      "accordion-07.svelte",
      "accordion-08.svelte",
      "accordion-09.svelte",
      "accordion-10.svelte",
      "accordion-11.svelte",
      "accordion-12.svelte",
      "accordion-13.svelte",
      "accordion-14.svelte",
      "accordion-15.svelte",
      "accordion-16.svelte",
      "accordion-17.svelte",
      "accordion-18.svelte",
      "accordion-19.svelte",
      "accordion-20.svelte",
    ],
    status: {
      todo: 0,
      ready: 20,
    },
  },
  ALERT: {
    directory: "alert",
    description: "A callout for displaying important information.",
    isnew: false,
    category: "ui",
    name: "Alert",
    components: [
      "alert-01.svelte",
      "alert-02.svelte",
      "alert-03.svelte",
      "alert-04.svelte",
      "alert-05.svelte",
      "alert-06.svelte",
      "alert-07.svelte",
      "alert-08.svelte",
      "alert-09.svelte",
      "alert-10.svelte",
      "alert-11.svelte",
      "alert-12.svelte",
    ],
    status: {
      todo: 0,
      ready: 12,
    },
  },
  AVATAR: {
    directory: "avatar",
    description: "An image element with a fallback for representing the user.",
    isnew: false,
    category: "ui",
    name: "Avatar",
    components: [
      "avatar-01.svelte",
      "avatar-02.svelte",
      "avatar-03.svelte",
      "avatar-04.svelte",
      "avatar-05.svelte",
      "avatar-06.svelte",
      "avatar-07.svelte",
      "avatar-08.svelte",
      "avatar-09.svelte",
      "avatar-10.svelte",
      "avatar-11.svelte",
      "avatar-12.svelte",
      "avatar-13.svelte",
      "avatar-14.svelte",
      "avatar-15.svelte",
      "avatar-16.svelte",
      "avatar-17.svelte",
      "avatar-18.svelte",
      "avatar-19.svelte",
      "avatar-20.svelte",
      "avatar-21.svelte",
      "avatar-22.svelte",
      "avatar-23.svelte",
    ],
    status: {
      todo: 0,
      ready: 23,
    },
  },
  BADGE: {
    directory: "badge",
    description: "A badge or a component that looks like a badge.",
    isnew: false,
    category: "ui",
    name: "Badge",
    components: [
      "badge-01.svelte",
      "badge-02.svelte",
      "badge-03.svelte",
      "badge-04.svelte",
      "badge-05.svelte",
      "badge-06.svelte",
      "badge-07.svelte",
      "badge-08.svelte",
      "badge-09.svelte",
      "badge-10.svelte",
      "badge-11.svelte",
      "badge-12.svelte",
      "badge-13.svelte",
    ],
    status: {
      todo: 0,
      ready: 13,
    },
  },
  BANNER: {
    directory: "banner",
    description: "A callout to show site-wide information.",
    isnew: false,
    category: "extra",
    name: "Banner",
    components: [
      "banner-01.svelte",
      "banner-02.svelte",
      "banner-03.svelte",
      "banner-04.svelte",
      "banner-05.svelte",
      "banner-06.svelte",
      "banner-07.svelte",
      "banner-08.svelte",
      "banner-09.svelte",
      "banner-10.svelte",
      "banner-11.svelte",
      "banner-12.svelte",
    ],
    status: {
      todo: 0,
      ready: 12,
    },
  },
  BREADCRUMB: {
    directory: "breadcrumb",
    description:
      "Displays the path to the current resource using a hierarchy of links.",
    isnew: false,
    category: "ui",
    name: "Breadcrumb",
    components: [
      "breadcrumb-01.svelte",
      "breadcrumb-02.svelte",
      "breadcrumb-03.svelte",
      "breadcrumb-04.svelte",
      "breadcrumb-05.svelte",
      "breadcrumb-06.svelte",
      "breadcrumb-07.svelte",
      "breadcrumb-08.svelte",
    ],
    status: {
      todo: 0,
      ready: 8,
    },
  },
  BUTTON: {
    directory: "button",
    description: "A button or a component that looks like a button.",
    isnew: false,
    category: "ui",
    name: "Button",
    components: [
      "button-01.svelte",
      "button-02.svelte",
      "button-03.svelte",
      "button-04.svelte",
      "button-05.svelte",
      "button-06.svelte",
      "button-07.svelte",
      "button-08.svelte",
      "button-09.svelte",
      "button-10.svelte",
      "button-11.svelte",
      "button-12.svelte",
      "button-13.svelte",
      "button-14.svelte",
      "button-15.svelte",
      "button-16.svelte",
      "button-17.svelte",
      "button-18.svelte",
      "button-19.svelte",
      "button-20.svelte",
      "button-21.svelte",
      "button-22.svelte",
      "button-23.svelte",
      "button-24.svelte",
      "button-25.svelte",
      "button-26.svelte",
      "button-27.svelte",
      "button-28.svelte",
      "button-29.svelte",
      "button-30.svelte",
      "button-31.svelte",
      "button-32.svelte",
      "button-33.svelte",
      "button-34.svelte",
      "button-35.svelte",
      "button-36.svelte",
      "button-37.svelte",
      "button-38.svelte",
      "button-39.svelte",
      "button-40.svelte",
      "button-41.svelte",
      "button-42.svelte",
      "button-43.svelte",
      "button-44.svelte",
      "button-45.svelte",
      "button-46.svelte",
      "button-47.svelte",
      "button-48.svelte",
      "button-49.svelte",
      "button-50.svelte",
      "button-51.svelte",
    ],
    status: {
      todo: 0,
      ready: 51,
    },
  },
  CHECKBOX: {
    directory: "checkbox",
    description:
      "A control allowing the user to toggle between checked and not checked.",
    isnew: false,
    category: "ui",
    name: "Checkbox",
    components: [
      "checkbox-01.svelte",
      "checkbox-02.svelte",
      "checkbox-03.svelte",
      "checkbox-04.svelte",
      "checkbox-05.svelte",
      "checkbox-06.svelte",
      "checkbox-07.svelte",
      "checkbox-08.svelte",
      "checkbox-09.svelte",
      "checkbox-10.svelte",
      "checkbox-11.svelte",
      "checkbox-12.svelte",
      "checkbox-13.svelte",
      "checkbox-14.svelte",
      "checkbox-15.svelte",
      "checkbox-16.svelte",
      "checkbox-17.svelte",
      "checkbox-18.svelte",
    ],
    status: {
      todo: 0,
      ready: 18,
    },
  },
  DIALOG: {
    directory: "dialog",
    description: "A popup that opens on top of the entire page.",
    isnew: false,
    category: "ui",
    name: "Dialog",
    components: [
      "dialog-01.svelte",
      "dialog-02.svelte",
      "dialog-03.svelte",
      "dialog-04.svelte",
      "dialog-05.svelte",
      "dialog-06.svelte",
      "dialog-07.svelte",
      "dialog-08.svelte",
      "dialog-09.svelte",
      "dialog-10.svelte",
      "dialog-11.svelte",
      "dialog-12.todo.svelte",
      "dialog-13.svelte",
      "dialog-14.svelte",
      "dialog-15.svelte",
      "dialog-16.todo.svelte",
      "dialog-17.todo.svelte",
      "dialog-18.svelte",
      "dialog-19.svelte",
      "dialog-20.svelte",
      "dialog-21.todo.svelte",
    ],
    status: {
      todo: 4,
      ready: 17,
    },
  },
  DROPDOWN: {
    directory: "dropdown",
    description: "No description available.",
    isnew: false,
    category: "Uncategorized",
    name: "Dropdown",
    components: [
      "dropdown-01.svelte",
      "dropdown-02.svelte",
      "dropdown-03.svelte",
      "dropdown-04.svelte",
      "dropdown-05.svelte",
      "dropdown-06.svelte",
      "dropdown-07.svelte",
      "dropdown-08.svelte",
      "dropdown-09.svelte",
      "dropdown-10.svelte",
      "dropdown-11.svelte",
      "dropdown-12.svelte",
      "dropdown-13.svelte",
      "dropdown-14.svelte",
      "dropdown-15.svelte",
    ],
    status: {
      todo: 0,
      ready: 15,
    },
  },
  INPUT: {
    directory: "input",
    description: "A native input element.",
    isnew: false,
    category: "ui",
    name: "Input",
    components: [
      "input-01.svelte",
      "input-02.svelte",
      "input-03.svelte",
      "input-04.svelte",
      "input-05.svelte",
      "input-06.svelte",
      "input-07.svelte",
      "input-08.svelte",
      "input-09.svelte",
      "input-10.svelte",
      "input-11.svelte",
      "input-12.svelte",
      "input-13.svelte",
      "input-14.svelte",
      "input-15.svelte",
      "input-16.svelte",
      "input-17.svelte",
      "input-18.svelte",
      "input-19.svelte",
      "input-20.svelte",
      "input-21.svelte",
      "input-22.svelte",
      "input-23.svelte",
      "input-24.svelte",
      "input-25.svelte",
      "input-26.svelte",
      "input-27.svelte",
      "input-28.svelte",
      "input-29.svelte",
      "input-30.svelte",
      "input-31.svelte",
      "input-32.svelte",
      "input-33.svelte",
      "input-34.svelte",
      "input-35.svelte",
      "input-36.svelte",
      "input-37.todo.svelte",
      "input-38.todo.svelte",
      "input-39.todo.svelte",
      "input-40.todo.svelte",
      "input-41.todo.svelte",
      "input-42.svelte",
      "input-43.svelte",
      "input-44.svelte",
      "input-45.svelte",
      "input-46.svelte",
      "input-47.todo.svelte",
      "input-48.todo.svelte",
      "input-49.todo.svelte",
      "input-50.todo.svelte",
      "input-51.svelte",
      "input-52.svelte",
      "input-53.svelte",
      "input-54.svelte",
      "input-55.svelte",
      "input-56.svelte",
      "input-57.todo.svelte",
      "input-58.todo.svelte",
      "input-59.todo.svelte",
    ],
    status: {
      todo: 12,
      ready: 47,
    },
  },
} as const;
export type COSSUIDirectories = typeof COSSUI_DIRECTORIES;
export const COMPONENT_STATES = {
  TODO: "todo",
  READY: "ready",
} as const;

export type ComponentState =
  (typeof COMPONENT_STATES)[keyof typeof COMPONENT_STATES];
