/* eslint-disable */
/**
 * !!!!!!!!!!
 * This file is auto-generated. Do not edit manually
 * Last generated at: 5/18/2026, 1:46:26 PM
 * To update, run: pnpm generate:registry --format
 * @version 0.1.0
 * !!!!!!!!!!
 */
export const COSSUI_DIRECTORIES = {
  ACCORDION: {
    category: 'ui',
    components: [
      'accordion-01.svelte',
      'accordion-02.svelte',
      'accordion-03.svelte',
      'accordion-04.svelte',
      'accordion-05.svelte',
      'accordion-06.svelte',
      'accordion-07.svelte',
      'accordion-08.svelte',
      'accordion-09.svelte',
      'accordion-10.svelte',
      'accordion-11.svelte',
      'accordion-12.svelte',
      'accordion-13.svelte',
      'accordion-14.svelte',
      'accordion-15.svelte',
      'accordion-16.svelte',
      'accordion-17.svelte',
      'accordion-18.svelte',
      'accordion-19.svelte',
      'accordion-20.svelte'
    ],
    description: 'A set of collapsible panels with headings and content.',
    directory: 'accordion',
    isnew: false,
    name: 'Accordion',
    status: {
      ready: 20,
      todo: 0
    }
  },
  ALERT: {
    category: 'ui',
    components: [
      'alert-01.svelte',
      'alert-02.svelte',
      'alert-03.svelte',
      'alert-04.svelte',
      'alert-05.svelte',
      'alert-06.svelte',
      'alert-07.svelte',
      'alert-08.svelte',
      'alert-09.svelte',
      'alert-10.svelte',
      'alert-11.svelte',
      'alert-12.svelte'
    ],
    description: 'A callout for displaying important information.',
    directory: 'alert',
    isnew: false,
    name: 'Alert',
    status: {
      ready: 12,
      todo: 0
    }
  },
  AVATAR: {
    category: 'ui',
    components: [
      'avatar-01.svelte',
      'avatar-02.svelte',
      'avatar-03.svelte',
      'avatar-04.svelte',
      'avatar-05.svelte',
      'avatar-06.svelte',
      'avatar-07.svelte',
      'avatar-08.svelte',
      'avatar-09.svelte',
      'avatar-10.svelte',
      'avatar-11.svelte',
      'avatar-12.svelte',
      'avatar-13.svelte',
      'avatar-14.svelte',
      'avatar-15.svelte',
      'avatar-16.svelte',
      'avatar-17.svelte',
      'avatar-18.svelte',
      'avatar-19.svelte',
      'avatar-20.svelte',
      'avatar-21.svelte',
      'avatar-22.svelte',
      'avatar-23.svelte'
    ],
    description: 'An image element with a fallback for representing the user.',
    directory: 'avatar',
    isnew: false,
    name: 'Avatar',
    status: {
      ready: 23,
      todo: 0
    }
  },
  BADGE: {
    category: 'ui',
    components: [
      'badge-01.svelte',
      'badge-02.svelte',
      'badge-03.svelte',
      'badge-04.svelte',
      'badge-05.svelte',
      'badge-06.svelte',
      'badge-07.svelte',
      'badge-08.svelte',
      'badge-09.svelte',
      'badge-10.svelte',
      'badge-11.svelte',
      'badge-12.svelte',
      'badge-13.svelte'
    ],
    description: 'A badge or a component that looks like a badge.',
    directory: 'badge',
    isnew: false,
    name: 'Badge',
    status: {
      ready: 13,
      todo: 0
    }
  },
  BANNER: {
    category: 'extra',
    components: [
      'banner-01.svelte',
      'banner-02.svelte',
      'banner-03.svelte',
      'banner-04.svelte',
      'banner-05.svelte',
      'banner-06.svelte',
      'banner-07.svelte',
      'banner-08.svelte',
      'banner-09.svelte',
      'banner-10.svelte',
      'banner-11.svelte',
      'banner-12.svelte'
    ],
    description: 'A callout to show site-wide information.',
    directory: 'banner',
    isnew: false,
    name: 'Banner',
    status: {
      ready: 12,
      todo: 0
    }
  },
  BREADCRUMB: {
    category: 'ui',
    components: [
      'breadcrumb-01.svelte',
      'breadcrumb-02.svelte',
      'breadcrumb-03.svelte',
      'breadcrumb-04.svelte',
      'breadcrumb-05.svelte',
      'breadcrumb-06.svelte',
      'breadcrumb-07.svelte',
      'breadcrumb-08.svelte'
    ],
    description: 'Displays the path to the current resource using a hierarchy of links.',
    directory: 'breadcrumb',
    isnew: false,
    name: 'Breadcrumb',
    status: {
      ready: 8,
      todo: 0
    }
  },
  BUTTON: {
    category: 'ui',
    components: [
      'button-01.svelte',
      'button-02.svelte',
      'button-03.svelte',
      'button-04.svelte',
      'button-05.svelte',
      'button-06.svelte',
      'button-07.svelte',
      'button-08.svelte',
      'button-09.svelte',
      'button-10.svelte',
      'button-11.svelte',
      'button-12.svelte',
      'button-13.svelte',
      'button-14.svelte',
      'button-15.svelte',
      'button-16.svelte',
      'button-17.svelte',
      'button-18.svelte',
      'button-19.svelte',
      'button-20.svelte',
      'button-21.svelte',
      'button-22.svelte',
      'button-23.svelte',
      'button-24.svelte',
      'button-25.svelte',
      'button-26.svelte',
      'button-27.svelte',
      'button-28.svelte',
      'button-29.svelte',
      'button-30.svelte',
      'button-31.svelte',
      'button-32.svelte',
      'button-33.svelte',
      'button-34.svelte',
      'button-35.svelte',
      'button-36.svelte',
      'button-37.svelte',
      'button-38.svelte',
      'button-39.svelte',
      'button-40.svelte',
      'button-41.svelte',
      'button-42.svelte',
      'button-43.svelte',
      'button-44.svelte',
      'button-45.svelte',
      'button-46.svelte',
      'button-47.svelte',
      'button-48.svelte',
      'button-49.svelte',
      'button-50.svelte',
      'button-51.svelte'
    ],
    description: 'A button or a component that looks like a button.',
    directory: 'button',
    isnew: false,
    name: 'Button',
    status: {
      ready: 51,
      todo: 0
    }
  },
  CHECKBOX: {
    category: 'ui',
    components: [
      'checkbox-01.svelte',
      'checkbox-02.svelte',
      'checkbox-03.svelte',
      'checkbox-04.svelte',
      'checkbox-05.svelte',
      'checkbox-06.svelte',
      'checkbox-07.svelte',
      'checkbox-08.svelte',
      'checkbox-09.svelte',
      'checkbox-10.svelte',
      'checkbox-11.svelte',
      'checkbox-12.svelte',
      'checkbox-13.svelte',
      'checkbox-14.svelte',
      'checkbox-15.svelte',
      'checkbox-16.svelte',
      'checkbox-17.svelte',
      'checkbox-18.svelte'
    ],
    description: 'A control allowing the user to toggle between checked and not checked.',
    directory: 'checkbox',
    isnew: false,
    name: 'Checkbox',
    status: {
      ready: 18,
      todo: 0
    }
  },
  'COMBOBOX.ORIGIN.OLD': {
    category: 'Uncategorized',
    components: [
      'dropdown-01.svelte',
      'dropdown-02.svelte',
      'dropdown-03.svelte',
      'dropdown-04.svelte',
      'dropdown-05.svelte',
      'dropdown-06.svelte',
      'dropdown-07.svelte',
      'dropdown-08.svelte',
      'dropdown-09.svelte',
      'dropdown-10.svelte',
      'dropdown-11.svelte',
      'dropdown-12.svelte',
      'dropdown-13.svelte',
      'dropdown-14.svelte',
      'dropdown-15.svelte'
    ],
    description: 'No description available.',
    directory: 'combobox.origin.old',
    isnew: false,
    name: 'Combobox.origin.old',
    status: {
      ready: 15,
      todo: 0
    }
  },
  DIALOG: {
    category: 'ui',
    components: [
      'dialog-01.svelte',
      'dialog-02.svelte',
      'dialog-03.svelte',
      'dialog-04.svelte',
      'dialog-05.svelte',
      'dialog-06.svelte',
      'dialog-07.svelte',
      'dialog-08.svelte',
      'dialog-09.svelte',
      'dialog-10.svelte',
      'dialog-11.svelte',
      'dialog-12.todo.svelte',
      'dialog-13.svelte',
      'dialog-14.svelte',
      'dialog-15.svelte',
      'dialog-16.todo.svelte',
      'dialog-17.todo.svelte',
      'dialog-18.svelte',
      'dialog-19.svelte',
      'dialog-20.svelte',
      'dialog-21.todo.svelte'
    ],
    description: 'A popup that opens on top of the entire page.',
    directory: 'dialog',
    isnew: false,
    name: 'Dialog',
    status: {
      ready: 17,
      todo: 4
    }
  },
  EMPTY: {
    category: 'ui',
    components: ['empty-01.svelte'],
    description: 'A container for displaying empty state information.',
    directory: 'empty',
    isnew: false,
    name: 'Empty',
    status: {
      ready: 1,
      todo: 0
    }
  },
  INPUT: {
    category: 'ui',
    components: [
      'input-01.svelte',
      'input-02.svelte',
      'input-03.svelte',
      'input-04.svelte',
      'input-05.svelte',
      'input-06.svelte',
      'input-07.svelte',
      'input-08.svelte',
      'input-09.svelte',
      'input-10.svelte',
      'input-11.svelte',
      'input-12.svelte',
      'input-13.svelte',
      'input-14.svelte',
      'input-15.svelte',
      'input-16.svelte',
      'input-17.svelte',
      'input-18.svelte',
      'input-19.svelte',
      'input-20.svelte',
      'input-21.svelte',
      'input-22.svelte',
      'input-23.svelte',
      'input-24.svelte',
      'input-25.svelte',
      'input-26.svelte',
      'input-27.svelte',
      'input-28.svelte',
      'input-29.svelte',
      'input-30.svelte',
      'input-31.svelte',
      'input-32.svelte',
      'input-33.svelte',
      'input-34.svelte',
      'input-35.svelte',
      'input-36.svelte',
      'input-37.todo.svelte',
      'input-38.todo.svelte',
      'input-39.todo.svelte',
      'input-40.todo.svelte',
      'input-41.todo.svelte',
      'input-42.svelte',
      'input-43.svelte',
      'input-44.svelte',
      'input-45.svelte',
      'input-46.svelte',
      'input-47.todo.svelte',
      'input-48.todo.svelte',
      'input-49.todo.svelte',
      'input-50.todo.svelte',
      'input-51.svelte',
      'input-52.svelte',
      'input-53.svelte',
      'input-54.svelte',
      'input-55.svelte',
      'input-56.svelte',
      'input-57.todo.svelte',
      'input-58.todo.svelte',
      'input-59.todo.svelte'
    ],
    description: 'A native input element.',
    directory: 'input',
    isnew: false,
    name: 'Input',
    status: {
      ready: 47,
      todo: 12
    }
  },
  NOTIFICATION: {
    category: 'Uncategorized',
    components: [
      'notification-01.svelte',
      'notification-02.svelte',
      'notification-03.svelte',
      'notification-04.svelte',
      'notification-05.svelte',
      'notification-06.svelte',
      'notification-07.svelte',
      'notification-08.svelte',
      'notification-09.svelte',
      'notification-10.svelte',
      'notification-11.svelte',
      'notification-12.svelte',
      'notification-13.svelte',
      'notification-14.svelte',
      'notification-15.svelte',
      'notification-16.svelte',
      'notification-17.svelte',
      'notification-18.svelte',
      'notification-19.todo.svelte',
      'notification-20.todo.svelte',
      'notification-21.svelte',
      'notification-22.svelte',
      'notification-23.svelte'
    ],
    description: 'No description available.',
    directory: 'notification',
    isnew: false,
    name: 'Notification',
    status: {
      ready: 21,
      todo: 2
    }
  },
  PAGINATION: {
    category: 'ui',
    components: [
      'pagination-01.svelte',
      'pagination-02.svelte',
      'pagination-03.svelte',
      'pagination-04.svelte',
      'pagination-05.svelte',
      'pagination-06.svelte',
      'pagination-07.svelte',
      'pagination-08.svelte',
      'pagination-09.svelte',
      'pagination-10.svelte',
      'pagination-11.svelte',
      'pagination-12.svelte'
    ],
    description: 'A pagination with page navigation, next and previous links.',
    directory: 'pagination',
    isnew: false,
    name: 'Pagination',
    status: {
      ready: 12,
      todo: 0
    }
  },
  POPOVER: {
    category: 'ui',
    components: [
      'popover-01.svelte',
      'popover-02.svelte',
      'popover-03.svelte',
      'popover-04.svelte',
      'popover-05.svelte',
      'popover-06.svelte',
      'popover-07.svelte',
      'popover-08.svelte',
      'popover-09.svelte'
    ],
    description: 'An accessible popup anchored to a button.',
    directory: 'popover',
    isnew: false,
    name: 'Popover',
    status: {
      ready: 9,
      todo: 0
    }
  },
  RADIO: {
    category: 'Uncategorized',
    components: [
      'radio-01.svelte',
      'radio-02.svelte',
      'radio-03.svelte',
      'radio-04.svelte',
      'radio-05.svelte',
      'radio-06.svelte',
      'radio-07.svelte',
      'radio-08.svelte',
      'radio-09.svelte',
      'radio-10.svelte',
      'radio-11.svelte',
      'radio-12.svelte',
      'radio-13.svelte',
      'radio-14.svelte',
      'radio-15.svelte',
      'radio-16.svelte',
      'radio-17.svelte',
      'radio-18.svelte',
      'radio-19.svelte'
    ],
    description: 'No description available.',
    directory: 'radio',
    isnew: false,
    name: 'Radio',
    status: {
      ready: 19,
      todo: 0
    }
  },
  SELECT: {
    category: 'ui',
    components: [
      'select-01.svelte',
      'select-02.svelte',
      'select-03.svelte',
      'select-04.svelte',
      'select-05.svelte',
      'select-06.svelte',
      'select-07.svelte',
      'select-08.svelte',
      'select-09.svelte',
      'select-10.svelte',
      'select-11.svelte',
      'select-12.svelte',
      'select-13.svelte',
      'select-14.svelte',
      'select-15.svelte',
      'select-16.svelte',
      'select-17.svelte',
      'select-18.svelte',
      'select-19.svelte',
      'select-20.svelte',
      'select-21.svelte',
      'select-22.svelte',
      'select-23.svelte',
      'select-24.svelte',
      'select-25.svelte',
      'select-26.svelte',
      'select-27.svelte',
      'select-28.svelte',
      'select-29.svelte',
      'select-30.svelte',
      'select-31.svelte',
      'select-32.svelte',
      'select-33.svelte',
      'select-34.svelte',
      'select-35.svelte',
      'select-36.svelte',
      'select-37.svelte',
      'select-38.svelte',
      'select-39.svelte',
      'select-40.svelte',
      'select-41.svelte',
      'select-42.svelte',
      'select-43.svelte',
      'select-44.svelte',
      'select-45.svelte',
      'select-46.todo.svelte',
      'select-47.todo.svelte',
      'select-48.svelte',
      'select-49.todo.svelte',
      'select-50.todo.svelte',
      'select-51.todo.svelte'
    ],
    description: 'A common form component for choosing a predefined value in a dropdown menu.',
    directory: 'select',
    isnew: false,
    name: 'Select',
    status: {
      ready: 46,
      todo: 5
    }
  },
  SLIDER: {
    category: 'ui',
    components: [
      'slider-01.svelte',
      'slider-02.svelte',
      'slider-03.svelte',
      'slider-04.svelte',
      'slider-05.svelte',
      'slider-06.svelte',
      'slider-07.svelte',
      'slider-08.svelte',
      'slider-09.svelte',
      'slider-10.svelte',
      'slider-11.svelte',
      'slider-12.svelte',
      'slider-13.svelte',
      'slider-14.svelte',
      'slider-15.svelte',
      'slider-16.svelte',
      'slider-17.svelte',
      'slider-18.svelte',
      'slider-19.svelte',
      'slider-20.svelte',
      'slider-21.svelte',
      'slider-22.svelte',
      'slider-23.svelte',
      'slider-24.svelte',
      'slider-25.svelte',
      'slider-26.svelte',
      'slider-27.svelte'
    ],
    description: 'An input where the user selects a value from within a given range.',
    directory: 'slider',
    isnew: false,
    name: 'Slider',
    status: {
      ready: 27,
      todo: 0
    }
  },
  SWITCH: {
    category: 'ui',
    components: [
      'switch-01.svelte',
      'switch-02.svelte',
      'switch-03.svelte',
      'switch-04.svelte',
      'switch-05.svelte',
      'switch-06.svelte',
      'switch-07.svelte',
      'switch-08.svelte',
      'switch-09.svelte',
      'switch-10.svelte',
      'switch-11.svelte',
      'switch-12.svelte',
      'switch-13.svelte',
      'switch-14.svelte',
      'switch-15.svelte',
      'switch-16.svelte',
      'switch-17.svelte'
    ],
    description: 'A control that indicates whether a setting is on or off.',
    directory: 'switch',
    isnew: false,
    name: 'Switch',
    status: {
      ready: 17,
      todo: 0
    }
  },
  TAB: {
    category: 'Uncategorized',
    components: [
      'tab-01.svelte',
      'tab-02.svelte',
      'tab-03.svelte',
      'tab-04.svelte',
      'tab-05.svelte',
      'tab-06.svelte',
      'tab-07.svelte',
      'tab-08.svelte',
      'tab-09.svelte',
      'tab-10.svelte',
      'tab-11.svelte',
      'tab-12.svelte',
      'tab-13.svelte',
      'tab-14.svelte',
      'tab-15.svelte',
      'tab-16.svelte',
      'tab-17.svelte',
      'tab-18.svelte',
      'tab-19.svelte',
      'tab-20.svelte'
    ],
    description: 'No description available.',
    directory: 'tab',
    isnew: false,
    name: 'Tab',
    status: {
      ready: 20,
      todo: 0
    }
  },
  TABLE: {
    category: 'ui',
    components: [
      'table-01.svelte',
      'table-02.svelte',
      'table-03.svelte',
      'table-04.svelte',
      'table-05.svelte',
      'table-06.svelte',
      'table-07.svelte',
      'table-08.svelte',
      'table-09.svelte',
      'table-10.svelte',
      'table-11.svelte',
      'table-12.svelte',
      'table-13.svelte',
      'table-14.svelte',
      'table-15.svelte',
      'table-16.svelte',
      'table-17.svelte',
      'table-18.svelte',
      'table-19.svelte',
      'table-20.svelte'
    ],
    description: 'A simple table component for displaying tabular data.',
    directory: 'table',
    isnew: false,
    name: 'Table',
    status: {
      ready: 20,
      todo: 0
    }
  },
  TEXTAREA: {
    category: 'ui',
    components: [
      'textarea-01.svelte',
      'textarea-02.svelte',
      'textarea-03.svelte',
      'textarea-04.svelte',
      'textarea-05.svelte',
      'textarea-06.svelte',
      'textarea-07.svelte',
      'textarea-08.svelte',
      'textarea-09.svelte',
      'textarea-10.svelte',
      'textarea-11.svelte',
      'textarea-12.svelte',
      'textarea-13.svelte',
      'textarea-14.svelte',
      'textarea-15.svelte',
      'textarea-16.svelte',
      'textarea-17.svelte',
      'textarea-18.svelte',
      'textarea-19.svelte'
    ],
    description: 'A native textarea element.',
    directory: 'textarea',
    isnew: false,
    name: 'Textarea',
    status: {
      ready: 19,
      todo: 0
    }
  },
  TIMELINE: {
    category: 'Uncategorized',
    components: [
      'timeline-01.svelte',
      'timeline-02.svelte',
      'timeline-03.svelte',
      'timeline-04.svelte',
      'timeline-05.svelte',
      'timeline-06.svelte',
      'timeline-07.svelte',
      'timeline-08.svelte',
      'timeline-09.svelte',
      'timeline-10.svelte',
      'timeline-11.svelte',
      'timeline-12.svelte'
    ],
    description: 'No description available.',
    directory: 'timeline',
    isnew: false,
    name: 'Timeline',
    status: {
      ready: 12,
      todo: 0
    }
  },
  TOOLTIP: {
    category: 'ui',
    components: [
      'tooltip-01.svelte',
      'tooltip-02.svelte',
      'tooltip-03.svelte',
      'tooltip-04.svelte',
      'tooltip-05.svelte',
      'tooltip-06.svelte',
      'tooltip-07.svelte',
      'tooltip-08.svelte',
      'tooltip-09.svelte',
      'tooltip-10.svelte',
      'tooltip-11.svelte',
      'tooltip-12.svelte'
    ],
    description:
      'A popup that appears when an element is hovered or focused, showing a hint for sighted users.',
    directory: 'tooltip',
    isnew: false,
    name: 'Tooltip',
    status: {
      ready: 12,
      todo: 0
    }
  },
  'TREE.OLD': {
    category: 'Uncategorized',
    components: [
      'tree-01.svelte',
      'tree-02.svelte',
      'tree-03.svelte',
      'tree-04.svelte',
      'tree-05.svelte',
      'tree-06.svelte',
      'tree-07.svelte',
      'tree-08.svelte'
    ],
    description: 'No description available.',
    directory: 'tree.old',
    isnew: false,
    name: 'Tree.old',
    status: {
      ready: 8,
      todo: 0
    }
  }
} as const;
export type COSSUIDirectories = typeof COSSUI_DIRECTORIES;
export const COMPONENT_STATES = {
  READY: 'ready',
  TODO: 'todo'
} as const;

export type ComponentState = (typeof COMPONENT_STATES)[keyof typeof COMPONENT_STATES];
