/// <reference types="node" />
import fs from 'node:fs/promises';
import path from 'node:path';
import userRegistry from './user-registry-particule-metadata.js';

export interface RegistryParticuleEntry {
    name?: string;
    description: string;
    // relative to src/lib/components/
    file?: string;
    // optional tags for categorization
    tags?: string[];
    npmDependencies?: string[];
    registryDependencies?: string[];
}

export type RegistryParticuleData = Record<string, RegistryParticuleEntry>;


const SOURCE_DIR = path.resolve('src/lib/components/examples');

const writeFlag = process.argv.includes('-w');
const writeArgIdx = process.argv.indexOf('-w');
const outputFile = writeArgIdx !== -1 && process.argv[writeArgIdx + 1] && !process.argv[writeArgIdx + 1].startsWith('-')
    ? process.argv[writeArgIdx + 1]
    : 'registry-particule.ts';

function toName(id: string): string {
    return id
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
}

async function scanExamples(): Promise<void> {
    const categories = await fs.readdir(SOURCE_DIR, { withFileTypes: true });
    const components: RegistryParticuleData = {};

    for (const entry of categories.sort((a, b) => a.name.localeCompare(b.name))) {
        if (!entry.isDirectory()) continue;

        const category = entry.name;
        const categoryPath = path.join(SOURCE_DIR, category);
        const files = (await fs.readdir(categoryPath)).sort();

        for (const file of files) {
            if (!file.endsWith('.svelte')) continue;

            const id = file.replace(/\.svelte$/, '');
            console.log(id)
            const meta = userRegistry[id];
            const component: RegistryParticuleEntry = {
                name: toName(id),
                description: meta?.description ?? '',
                file: `examples/${category}/${file}`,
                tags: meta ? meta.tags : [],
                npmDependencies: [],
                registryDependencies: []
            };

            components[id] = component;
        }
    }

    const json = JSON.stringify(components, null, 4)
    const output = `
/**
 * This file is auto-generated by scripts/createParticuleRegistry.ts
 * Do not edit this file directly.
 * To update, edit the source files in scripts/user-registry-particule-metadata.ts and run: pnpm generate:registry
 * @version 0.1.0
 * !!!!!!!!!!
 */
export interface RegistryParticuleEntry {
    name: string;
    description: string;
    // relative to src/lib/components/
    file: string;
    // optional tags for categorization
    tags: string[];
    npmDependencies: string[];
    registryDependencies: string[];
}

export type RegistryParticuleData = Record<string, RegistryParticuleEntry>;
export const particules: RegistryParticuleData = ${json};
`;

    if (writeFlag) {
        await fs.writeFile(outputFile, output);
        console.log(`Written to ${outputFile}`);
    } else {
        console.log(output);
    }
}

scanExamples().catch((err) => {
    console.error(err);
    process.exit(1);
});
