/// <reference types="node" />
import fs from 'node:fs/promises';
import path from 'node:path';
import userRegistry from './custom-particule-metadata.js';

export interface RegistryParticuleEntry {
    name?: string;
    description: string;
    // relative to src/lib/components/
    file?: string;
    // optional tags for categorization
    tags?: string[];
    npmDependencies?: string[];
    registryDependencies?: string[];
    component: string;
}

export type RegistryParticuleData = Record<string, RegistryParticuleEntry>;


const SOURCE_DIR = path.resolve('src/lib/components/particles');

const writeFlag = process.argv.includes('-w');
const writeArgIdx = process.argv.indexOf('-w');
const outputFile = writeArgIdx !== -1 && process.argv[writeArgIdx + 1] && !process.argv[writeArgIdx + 1].startsWith('-')
    ? process.argv[writeArgIdx + 1]
    : 'registry-particule.ts';

function toName(id: string): string {
    return id
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
}

// no spaces
function toComponentName(id: string): string {
    return id
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

const isNumbered = (file: string): boolean => /-\d+\.svelte$/.test(file);

async function scanExamples(): Promise<void> {
    const exampleFolders = await fs.readdir(SOURCE_DIR, { withFileTypes: true });

    const components: RegistryParticuleData = {};

    let imports=""

    for (const folder of exampleFolders.sort((a, b) => a.name.localeCompare(b.name))) {
        if (!folder.isDirectory()) continue;

        const componentName = folder.name;
        const componentPath = path.join(SOURCE_DIR, componentName);

        // real all the files in the folder
        const files = (await fs.readdir(componentPath)).filter(isNumbered).sort();

        for (const file of files) {

            const id = file.replace(/\.svelte$/, '');
            const meta = userRegistry[id];
            
            const component: RegistryParticuleEntry = {
                name: toName(id),
                description: meta?.description ?? '',
                file: `${file.replace('.svelte', '')}`,
                tags: meta ? meta.tags : [],
                npmDependencies: [],
                registryDependencies: [],
                component: toComponentName(id)
            };

            imports+=`import ${toComponentName(id)} from "$lib/components/particles/${componentName}/${file}"\n`

            components[id] = component;
        }
    }


    const tsObj = Object.entries(components).map(([id, e]) => `  '${id}': {
        component: ${toComponentName(id)},
        description: ${JSON.stringify(e.description)},
        file: '${e.file}',
        name: ${JSON.stringify(e.name)},
        npmDependencies: ${JSON.stringify(e.npmDependencies)},
        registryDependencies: ${JSON.stringify(e.registryDependencies)},
        tags: ${JSON.stringify(e.tags)}
    }`).join(',\n');

// const file = `${imports}\n\nexport const registry = {\n${entries}\n};\n`;
    // const json = JSON.stringify(components, null, 4)
    const output = `
/**
 * This file is auto-generated by scripts/createParticuleRegistry.ts
 * Do not edit this file directly.
 * To update, edit the source files in scripts/user-registry-particule-metadata.ts and run: pnpm generate:registry
 * @version 0.1.0
 * !!!!!!!!!!
 */
${imports}
import type { Component } from 'svelte';
export interface RegistryParticuleEntry {
    name: string;
    description: string;
    // relative to src/lib/components/
    file: string;
    // optional tags for categorization
    tags: string[];
    npmDependencies: string[];
    registryDependencies: string[];
    component: Component
}

export type RegistryParticuleData = Record<string, RegistryParticuleEntry>;
const allParticles: RegistryParticuleData = {${tsObj}};
export { allParticles };
`;

    if (writeFlag) {
        await fs.writeFile(outputFile, output);
        console.log(`Written to ${outputFile}`);
    } else {
        console.log(output);
    }
}

scanExamples().catch((err) => {
    console.error(err);
    process.exit(1);
});
