/// <reference types="node" />
import fs from 'node:fs/promises';
import path from 'node:path';
import {custom_components_metadata} from './custom-component-metadata.js';

export interface RegistryUIEntry {
    name?: string;
    description: string;
    folder?: string; // relative to src/lib/components/ui/
    category: "ui" | "origin-ui" | "bits-ui" | "extra"; // for now, just a simple category to separate "core" UI components from extra ones
    isnew?: boolean; // wether this is a new component that should be highlighted in the UI
    istodo?: boolean; // wether this is an identified component that needs to be worked on
    npmDependencies?: string[];
    registryDependencies?: string[];
}

export type RegistryUiData = Record<string, RegistryUIEntry>;


const SOURCE_DIR = path.resolve('src/lib/components/ui');

const writeFlag = process.argv.includes('-w');
const writeArgIdx = process.argv.indexOf('-w');
const outputFile = writeArgIdx !== -1 && process.argv[writeArgIdx + 1] && !process.argv[writeArgIdx + 1].startsWith('-')
    ? process.argv[writeArgIdx + 1]
    : 'registry-components.ts';

function toName(id: string): string {
    return id
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
}

async function fileExists(path: string): Promise<boolean> {
    try {
        await fs.access(path);
        return true;
    } catch {
        return false;
    }
}

async function scanExamples(): Promise<void> {
    const categories = await fs.readdir(SOURCE_DIR, { withFileTypes: true });
    const components: RegistryUiData = {};

    for (const entry of categories.sort((a, b) => a.name.localeCompare(b.name))) {
        if (!entry.isDirectory()) continue;

        const category = entry.name;
        const indexPath = path.join(SOURCE_DIR, category, "index.ts");
        if (await fileExists(indexPath)) {

            const meta = custom_components_metadata[category];
            const component: RegistryUIEntry = {
                name: toName(category),
                category: meta?.category ?? 'ui',
                description: meta?.description ?? '',
                folder: `${category}`,
                isnew: meta?.isnew ?? false,
                  istodo: meta?.istodo ?? false,
                npmDependencies: [],
                registryDependencies: []
            };

            components[category] = component;

        }
    }

    const json = JSON.stringify(components, null, 4)
    const output = `
/**
 * This file is auto-generated by scripts/createUiRegistry.ts
 * Do not edit this file directly.
 * To update, edit the source files in scripts/user-registry-ui-metadata.ts and run: pnpm generate:registry
 * @version 0.1.0
 * !!!!!!!!!!
 */
export interface RegistryUIEntry {
    name: string;
    description: string;
    folder: string; // relative to src/lib/components/ui/
    category: "ui" | "origin-ui" | "bits-ui" | "extra"; // for now, just a simple category to separate "core" UI components from extra ones
    isnew: boolean; // whether this is a new component that should be highlighted in the UI
    istodo: boolean; // wether this is an identified component that needs to be worked on
    npmDependencies: string[];
    registryDependencies: string[];
}

export type RegistryUiData = Record<string, RegistryUIEntry>;
const allComponents: RegistryUiData = ${json};
export { allComponents };
`;

    if (writeFlag) {
        await fs.writeFile(outputFile, output);
        console.log(`Written to ${outputFile}`);
    } else {
        console.log(output);
    }
}

scanExamples().catch((err) => {
    console.error(err);
    process.exit(1);
});
